### ISSUE TITLE
igor: reservation power command error

### ISSUE THREAD

**Issue by csymonds** [sandia-minimega/minimega#1013]
power off minimega reservation (e.g. non-cobbler) then power on the same reservation results in the following error:
2017/10/18 09:23:48 ERROR power.go:74: power command [cobbler system poweron --name en12] returned exit status 1
Please fix.

**Comment by csymonds** [comment]
@jcrussell I have been unable to recreate this issue. Are you still seeing this?

**Comment by jcrussell** [comment]
Yes but rarely. We may just want to add a retry.
