### ISSUE TITLE
igor: Allow Multiple allocations to share a vlan

### ISSUE THREAD

**Issue by csymonds** [sandia-minimega/minimega#1064]
from Joseph Kenny:
I think we should prioritize adding a feature to igor that allows multiple allocations to share a vlan.  Besides working around any igor/cobbler issues I think igor only creates contiguous allocations, so there may still be a use case for stitching together small allocations.

**Comment by jcrussell** [comment]
igor allows non-contiguous reservations. Since we cap reservation times based on the size of the reservation, this would allow someone to get around those limits.

I suggest closing this.
