### ISSUE TITLE
igor: smarter non-contiguous allocations

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1066]
It would be helpful if igor could reserve non-contiguous blocks of nodes. We don't have a way to "defrag" the cluster so the required number of nodes may be free but they are split up.

In order to make scripting easier, igor should generate a hosts file for each reservation so that the nodes are contiguously indexed. For example:

```
igor sub -r foo -n 50 ...
....
ssh foo.0
ssh foo.1
...
ssh foo.49
```

**Comment by afbagwell** [comment]
This enhancement will be reviewed by the Igor 2.x dev team, but it will not be implemented in Igor 1.x.
