### ISSUE TITLE
-enable-kvm shows up twice for booted vms

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1076]
```
minimega$ vm config cdrom tiny.iso
minimega$ vm launch kvm tiny
minimega$ vm start tiny
```
```
ps aux | grep qemu
qemu-system-x86_64 -enable-kvm -enable-kvm -name 9 -m 2048 -nographic -balloon none -vnc unix:/tmp/minimega/9/vnc -smp ~snip~
```
I'm guessing by default mini uses /usr/bin/kvm which adds `-enable-kvm`  in addition to mini
```
#!/bin/sh
exec qemu-system-x86_64 -enable-kvm "$@"
```

**Comment by jcrussell** [comment]
Yup: https://github.com/sandia-minimega/minimega/blob/master/src/minimega/kvm.go#L882

Does it hurt to have it twice? We can probably remove it.

**Comment by mkunz7** [comment]
Doesn't hurt to call it twice afaik, just painful to look at.

Ideally I think we should by default call `qemu-system-x86_64` instead of `kvm` and have a `vm config enablekvm` which by default is set to true.
