### ISSUE TITLE
vnc: stuck keys

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1082]
VNC functions don't work properly with the lxde display environment.

install ubuntu 16.04
```apt-get install lxde```

Examples
Control +c will run about 19 times
```
500000000:KeyEvent,true,Control_L
1000000000:KeyEvent,true,c
1000000000:KeyEvent,false,c
500000000:KeyEvent,false,Control_L
```
Control +c will run 1-3 times
```
500000000:KeyEvent,true,Control_L
500000000:KeyEvent,true,c
500000000:KeyEvent,false,c
500000000:KeyEvent,false,Control_L
```
control+shift+t (open a new terminal tab) and type a command
```
50000000:KeyEvent,true,Control_L
50000000:KeyEvent,true,Shift_L
50000000:KeyEvent,true,t
50000000:KeyEvent,false,t
50000000:KeyEvent,false,Control_L
50000000:KeyEvent,false,Shift_L
```
```
50000000:KeyEvent,true,e
50000000:KeyEvent,false,e
50000000:KeyEvent,true,c
50000000:KeyEvent,false,c
50000000:KeyEvent,true,h
50000000:KeyEvent,false,h
50000000:KeyEvent,true,o
50000000:KeyEvent,false,o
50000000:KeyEvent,true,space
50000000:KeyEvent,false,space
50000000:KeyEvent,true,h
50000000:KeyEvent,false,h
50000000:KeyEvent,true,i
50000000:KeyEvent,false,i
50000000:KeyEvent,true,Return
50000000:KeyEvent,false,Return
```
On each re-run the case will alternate from `echo hi` to `ECHO HI` like it never saw `KeyEvent,false,Shift_L` 

If run as one chunk of commands it's fine.
```
50000000:KeyEvent,true,Control_L
50000000:KeyEvent,true,Shift_L
50000000:KeyEvent,true,t
50000000:KeyEvent,false,t
50000000:KeyEvent,false,Control_L
50000000:KeyEvent,false,Shift_L
50000000:KeyEvent,true,e
50000000:KeyEvent,false,e
50000000:KeyEvent,true,c
50000000:KeyEvent,false,c
50000000:KeyEvent,true,h
50000000:KeyEvent,false,h
50000000:KeyEvent,true,o
50000000:KeyEvent,false,o
50000000:KeyEvent,true,space
50000000:KeyEvent,false,space
50000000:KeyEvent,true,h
50000000:KeyEvent,false,h
50000000:KeyEvent,true,i
50000000:KeyEvent,false,i
50000000:KeyEvent,true,Return
50000000:KeyEvent,false,Return
```

This may have been a prexisting issue before the latest changes and doesn't seem to affect anything besides lxde.

**Comment by jcrussell** [comment]
Did this ever get resolved? Should we close since it only seems to affect lxde?

**Comment by mkunz7** [comment]
Not resolved

**Comment by jcrussell** [comment]
Updated novnc to latest release (#1110), we'll see if that fixes it.

**Comment by djfritz** [comment]
What is the keyboard repeat rate set to? Holding ctrl+c down for 1 second on my actual keyboard issues ctrl-c many times as well...

**Comment by mkunz7** [comment]
Ok so I can just get around that with a false event immediately following cool. The echo hi example is still an issue though.

**Comment by djfritz** [comment]
Hmm - I wonder what if any timing constraints there are in the rfb protocol or qemu's implementation of it. 

@jcrussell Let's replicate this and get a PCAP to confirm that everything is going over the wire correctly to qemu and poke from there.

**Comment by mkunz7** [comment]
Closing. To prevent this issue, capitalize any key presses when shift is held down.

```
50000000:KeyEvent,true,Control_L
50000000:KeyEvent,true,Shift_L
50000000:KeyEvent,true,T
50000000:KeyEvent,false,T
50000000:KeyEvent,false,Control_L
50000000:KeyEvent,false,Shift_L
```
instead of 
```
50000000:KeyEvent,true,Control_L
50000000:KeyEvent,true,Shift_L
50000000:KeyEvent,true,t
50000000:KeyEvent,false,t
50000000:KeyEvent,false,Control_L
50000000:KeyEvent,false,Shift_L
```
