### ISSUE TITLE
igor: schedule bug

### ISSUE THREAD

**Issue by csymonds** [sandia-minimega/minimega#1104]
the schedule file for igor appears to be intermittently getting erased for an unknown reason, causing all reservation to be susceptible to being reserved over.

**Comment by csymonds** [comment]
We can either change how we handle the schedule file or do away with the schedule file altogether. My hope is to maybe allow an attempt to rebuild the schedule file based on the reservation file if something goes wrong.

**Comment by jcrussell** [comment]
See #1091.
