### ISSUE TITLE
minimega: reserved words

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#111]
Original [issue 111](https://code.google.com/p/minimega/issues/detail?id=111) created by djfritz on 2015-02-04T22:44:42.000Z:

Users shouldn't be able to name vms/taps/bridges/... using reserved words. Currently, the only reserved word is &quot;all&quot; which is used for wildcards.

**Comment by jcrussell** [comment]
Isn't this something we should have before 2.0? It *shouldn't* be too hard to add.

**Comment by djfritz** [comment]
We should have time to get this in if you want. Maybe populating a []string of reserved words at runtime in the init() in main.go?
