### ISSUE TITLE
minimega: GRE tunnels appear in containers

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1124]
GRE tunnels appear in containers as interfaces. Needs investigating.

**Comment by jcrussell** [comment]
Related: https://github.com/lxc/lxd/issues/3338

**Comment by djfritz** [comment]
I don't think this is impacting device name ordering or anything like that, so this is probably just something we ignore in exactly the same way lxc does. Thoughts?

**Comment by jcrussell** [comment]
Doesn't seem like there's a good solution other than to ignore.
