### ISSUE TITLE
web: Update Documentation

### ISSUE THREAD

**Issue by onaclov2000** [sandia-minimega/minimega#1188]
Documentation on the http://minimega.org/articles/tutorials/vmbetter.article webpage for how to create the wireshark.iso and run uses the web 9001 command, this is no longer a working command post 2.3 release.

**Comment by onaclov2000** [comment]
http://minimega.org/articles/miniweb.article
I discovered I should be using miniweb, I initially tried starting via bin/miniweb but that didn't work, after using -console flag and checking, I saw a permission denied, tried sudo and it worked.

```
sudo bin/miniweb
```

**Comment by jcrussell** [comment]
Good catch, that documentation has been wrong for a while.

**Comment by jcrussell** [comment]
Fixed in #1207.
