### ISSUE TITLE
Virtualbox Running

### ISSUE THREAD

**Issue by onaclov2000** [sandia-minimega/minimega#1190]
For searchability:

    unable to connect to qmp socket: qmp timeout

In my case I had virtualbox running (vagrant) and had to kill it, once I did that, no more errors to get the VM's started using the wireshark tutorial. (except the web command which is replaced by miniweb)

**Comment by jcrussell** [comment]
We assume that minimega doesn't have to contend with other VM management tools -- should close unless we plan to update the documentation to reflect this.
