### ISSUE TITLE
minicli: fatal logging 

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#1191]
minimega[minimega]$ read foo.mm
    2018/10/16 01:09:59 FATAL minicli.go:191: invalid command: `namespace "minimega" vm config qemu-override '-usb -device usb-ehci,id=ehci -device usb-tablet,bus=usb-bus.0' ''`

This seems to be an error. I have a malformed command in a script and I get minimega to fatal out. 

@jcrussell

**Comment by jcrussell** [comment]
minimega treats it as a fatal error if the commands that it generates under the hood are invalid when the user-entered command was valid (i.e. we should never take a correct command and generate an incorrect command). Definitely a bug though.

Is this on master?

**Comment by djfritz** [comment]
This is with 2.5 release

**Comment by jcrussell** [comment]
Confirmed on master. Ouch -- 2.5.1?

Can you test with #1184? I tested this specific command and it worked for me on that branch.

**Comment by jcrussell** [comment]
Should be fixed by #1184.
