### ISSUE TITLE
rfbplay: support auto-transcoding with ffmpeg runtime dependency

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#120]
Original [issue 120](https://code.google.com/p/minimega/issues/detail?id=120) created by djfritz on 2015-02-13T20:49:14.000Z:

support a one liner production to transcode an rfb file to mp4 with ffmpeg. 

Something like:

rfbplay -transcode foo.fb out.mp4

Which would start the local webserver according to other flags and invoke ffmpeg with something like:

ffmpeg -f mjpeg -r 10 -i http://localhost:9004/foo.fb out.mp4

Then quit.

**Comment by jcrussell** [comment]
There are a few libavcodec wrappers for Go. None seem that complete, we could add our own.

Low priority though.

**Comment by djfritz** [comment]
The libavcodec wrappers are /insane/ and unnecessary for this tool. We're just going to have an external dependency on ffmpeg and call out to it in the same way minimega invokes qemu.
