### ISSUE TITLE
minimega: add `ns bridge tunnel`

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1231]
Not sure exactly what the API should be but it should create a mesh of GRE tunnels across hosts in the namespace.

**Comment by activeshadow** [comment]
Curious what your use case is for this @jcrussell? I've been wondering if GRE tunnels can trunk VLANs between hosts. If so, a GRE mesh would support running a minimega cluster in cloud providers that support nested virtualization. This particular use case would require all the compute nodes to be in the GRE mesh though, not just nodes in a particular namespace.

**Comment by jcrussell** [comment]
Yeah -- a GRE mesh would allow us to run on clusters/cloud providers that don't allow VLAN tagging.

**Comment by activeshadow** [comment]
@jcrussell just had a chance to test this. When I run it in a namespace with multiple hosts it just hangs. Have you experienced this? I can provide more specifics if need be.

**Comment by jcrussell** [comment]
That's strange, haven't seen that before.
