### ISSUE TITLE
minimega: container overlay does not behave correctly when rootfs is on NFS.

### ISSUE THREAD

**Issue by activeshadow** [sandia-minimega/minimega#1234]
We have a minimega cluster that has the head node hosting an NFS share and all the compute nodes mounting the share. Each instance of minimega uses the mounted NFS share as the filepath.

Running virtual machines from images on the NFS share works fine. However, running containers from root filesystems on the NFS share does not. The containers boot, but we get a lot of `Operation not supported` errors when trying to create files or directories in certain existing directories.

For example, we have a root filesystem for minirouter, and when we start the container we see the following when the `/init` script is run and tries to start SSH.

```
mkdir: cannot create directory '/var/run/sshd': Operation not supported
Missing privilege separation directory: /run/sshd
```

The `/init` script also tries to start `miniccc` and `minirouter`, and both also fail with similar errors, which were printed in `/miniccc.log` and `/minirouter.log`.

```
FATAL main.go:84: mkdir base path: mkdir /tmp/miniccc: operation not supported
FATAL minirouter.go:75: mkdir base path: mkdir /tmp/minirouter: operation not supported
```

It's interesting that the `miniccc.log` and `minirouter.log` files can be created in the root directory, but files and directories cannot be created in other directories, like `/tmp` and `/var/run`.

Alternatively, we considered doing away with the NFS share and using minimega's file transfer support, but when I tested getting a root filesystem via `file get minirouter` I got an error along the lines of `Error (minimega1): file not found`. Some portions of the root filesystem had been retrieved, so it doesn't seem to be an issue with transferring directories. Perhaps it's an issue with static links? I also tried using the `file:` prefix when configuring the container's filesystem, but that resulted in the following.

```
vm config filesystem file:minirouter
Error (): file not found
```

How have users been sharing container root filesystems across a minimega cluster if these two techniques aren't working?

**Comment by jcrussell** [comment]
We generally pass around a tarball for the container and extract it on each host since there are special files in the container filesystem that don't play nice with NFS. You should be able to use the `tar:` prefix which will extract to the `iomBase` path (after doing the same behavior as the `file:` prefix). If the `iomBase` path is in an NFS share, you'll probably run into the same issue.

**Comment by jcrussell** [comment]
I'll make a note to add documentation for the `tar:` prefix [here](http://tip.minimega.org/articles/file.article).

The `iomBase` directory is `/tmp/minimega/files` by default. If you put a `containerfs.tar.gz` in that directory on any node, you can then use:

```
vm config filesystem tar:containerfs.tar.gz
```

And minimega will automatically fetch the file, untar it, and use it for the container's filesystem.

**Comment by jcrussell** [comment]
I don't think we have a solution other than avoid doing this.

**Comment by activeshadow** [comment]
@jcrussell I think the solution is to use the `tar:` prefix approach like you described above. :+1:
