### ISSUE TITLE
minirouter: any plans for simple firewall support?

### ISSUE THREAD

**Issue by activeshadow** [sandia-minimega/minimega#1236]
#344 mentioned including a simple firewall in the container based router, but iptables isn't present in the defacto `uminirouter` container root filesystem and the `router` API doen't include any subcommands for firewall rules.

Just curious if there's any plans for this? I'm fine with creating a custom minirouter configuration that includes `iptables` and adding rules via `cc exec`. Was just curious if there were any plans for firewall support in the API in the future.

**Comment by jcrussell** [comment]
I remember we started on this and found some issue with containers and iptables. Possibly that there wasn't a separation between the host's iptables and the container's.

@djfritz

**Comment by jcrussell** [comment]
Yeah, we've resorted to a VM in the past when we needed a firewall and then setup `iptables` via `cc exec`.

I think @aherna was starting to work on a few `iptables` subcommands for the `router` API. It would be good to hash out what commands would be useful to wrap or whether it should just support raw `iptables` commands.

**Comment by aherna** [comment]
@activeshadow I made a minirouter kernal/init pair that has iptables. You can do cc exec to add the pertinent rules. We could add some sort of wrapper to stream line the process without cc exec, just depends on how advanced the rules we would want to create are.

ie would could do like cisco style with acls 
access-list access_list_name [ line line_number ] extended { deny | permit } protocol_argument source_address_argument dest_address_argument [ log [[ level ]

access-list OUTSIDE extended permit tcp any host 10.1.1.5 eq www

**Comment by mkunz7** [comment]
For what it's worth. I installed iptables in an alpine container and from what I can tell simple port blocks don't seem to affect the host.
