### ISSUE TITLE
minimega: vm qmp can lock up mini

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1259]
```
vm config disk /home/ubuntu/test.qcow
vm launch kvm test
vm start test
vm qmp test a
```
The last command causes minimega's console to hang. If you control+c and reattach you will be unable to issue any future minimega commands including nuke. Miniweb will also stop showing vms.

**Comment by jcrussell** [comment]
We've seen this before with invalid JSON caused by quoting issues. We should probably json encode/decode the second argument to make sure that it's a valid JSON object.
