### ISSUE TITLE
ron/miniccc unable to send/fetch files/folders > 512kB over serial

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1262]
```
mkdir C:\logs
fsutil file createnew C:\logs\test100kb.txt 100000
fsutil file createnew C:\logs\test500kb.txt 500000
```

```
cc recv C:\\logs\\*.txt
```

If the logs folder is >512kB it will cause miniccc to only fetch a partial subset of the data from a partial subset of the cc clients. In my case 5/30 cc clients responded with <500kB data each. I haven't tested using ip instead of serial.

**Comment by jcrussell** [comment]
We should implement file chunking like we do in `iomeshage`.

**Comment by djfritz** [comment]
This is a duplicate of #1332. Closing.

**Comment by jcrussell** [comment]
#1332 is the PR that would close this issue.

**Comment by djfritz** [comment]
#1332 is merged, closing.
