### ISSUE TITLE
minimega: vnc play cant play over a mesh

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1264]
```
mesh dial server1
mesh dial server2
mesh dial server3
ns add-hosts server1,server2,server3
vm config disk /home/ubuntu/win.qcow
vm launch kvm win[0-100]
vm start all
```
```
vnc play win[0-100] /home/ubuntu/test.vnc
```
If you log into the servers individually, hop on mini, and type ```vnc play <tab``` it lists all the vms on that server, but if you try to use the all command it fails.
```
vnc play all /home/ubuntu/test.vnc
```

**Comment by jcrussell** [comment]
We've been moving away from calling commands directly on the non-head nodes. `vnc play all` from the head node should work. Is there a reason to call it from another node?

**Comment by mkunz7** [comment]
I can't get vnc play all to work from the head node

**Comment by jcrussell** [comment]
Is `/home/ubuntu/test.vnc` on all the nodes?

**Comment by mkunz7** [comment]
each node spits out a 
```
Error (server): vm not found: all
```
doesnt matter if I use iomesh to get the vnc file or scp the file to all the nodes

**Comment by jcrussell** [comment]
What version of minimega are you using?

**Comment by jcrussell** [comment]
This seems to work correctly on master, please try to reproduce.

**Comment by mkunz7** [comment]
I was running 2.4. Playback to all works on master :)

Can we make it so I don't have to distribute the vnc file to the node first?

```
shell cp /home/ubuntu/vnctest.vnc /data/mmfiles/
mesh send all file get vnctest.vnc
vnc play all vnctest.vnc
```

**Comment by jcrussell** [comment]
`vnc play all` wasn't added until [v2.5](http://minimega.org/releases/minimega-2.5.article).
