### ISSUE TITLE
Feature Request: Less cowbell

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1265]
Double clicking on any of miniwebs tabs is a pretty natural tendency of mine. Idk how many times I've had that loud cowbell/moo just blare through my speakers as loud as humanly possible in a quiet room.

tldr less cowbell please

**Comment by mkunz7** [comment]
I'm thinking:
```
audioElement.volume = 0.1;
```

**Comment by jcrussell** [comment]
Closed by #1266.
