### ISSUE TITLE
Feature Request: enable mesh send when only one host exists in the active namespace

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1268]
I know we are trying to force people to use namespaces, but is there a reason why we can't allow various ```mesh send``` commands like ```vm launch``` and ```read``` when there is only one node in a namespace or the namespace is empty? Seems like we are unnecessarily limiting the capabilities of mesh.

**Comment by djfritz** [comment]
We do indeed change some mesh command behavior while in a namespace but those shouldn't be a part of the list of things that do that. What is it you're trying to do? There likely is a 'namespace'-y way to do it.

**Comment by mkunz7** [comment]
There are namespace aware ways of doing this it just adds an extra few steps. 

Say we have a network/qemu-override/qcow that only exists/works on one node. 
In the past I would just be able to use mesh send vm launch on that node and things would be good. 

With the new version I can't easily tell ```vm launch``` to place a vm on a certain node. I now have to create a namespace just for that node on the mesh, hop in that namespace, make my vm config, deploy it, and hop out of that namespace.

**Comment by djfritz** [comment]
vm config schedule <host>

Should do what you need

https://tip.minimega.org/articles/api.article#TOC_4.46.

**Comment by mkunz7** [comment]
Ahhhhhhh. We're still removing the ability to run read files though from the mesh. 

Can we add a warn if the node you are trying to schedule on is not in your namespace? Instead of launching them on the local box. 

```
vm config disk image.qcow
vm config schedule doesnotexist
vm launch kvm a,b,c
vm start all
```

**Comment by djfritz** [comment]
Yep that’s an easy fix

**Comment by jcrussell** [comment]
This is the short-circuit that logs a warning if you only have a single node in the namespace:

https://github.com/sandia-minimega/minimega/blob/4d3808de3619bae7509c7f82ce11ee2ac8c6b533/src/minimega/scheduler.go#L45-L51

I guess we could walk the schedule/coschedule requirements and abort the scheduling if they are violated.

**Comment by mkunz7** [comment]
I work with some end of life servers that have a tendency to have hardware issues. Entire servers go non responsive, but are still running vms and respond via the mesh. One of the things I could do in the past was issue a kill to all the vms running on that server with mesh send. With the new scheduling I’m not sure how to do that.

**Comment by jcrussell** [comment]
`vm kill <name>` from the head node will kill an individual VM on whatever node it runs on in the namespace. `vm kill all` will kill all the VMs in the namespace across all nodes. Under the hood, it uses meshage so these should work for this.

**Comment by djfritz** [comment]
And if you want to do it all, `clear all` will delete all vms, taps, etc., (basically everything) in all namespaces. It basically tries to get you back to a starting state.

**Comment by jcrussell** [comment]
You can also do `mesh send <host> namespace <namespace> vm kill all`. Is that not working?

**Comment by mkunz7** [comment]
If I start win[0-999] I won't know the names of the vms that are sitting on that one node since it is determined by the scheduler. So now I need to parse vm info and issue vm kills for each vm individually, and when the box is hanging getting one command across is hard enough let alone 70. 

If I understand correctly, if that node is in the same namespace as everyone else vm kill all will issue the commands on all the nodes, so now I'm back to creating separate namespaces for every node.

**Comment by djfritz** [comment]
I'm confused - your earlier comment was about killing all the vms on a particular node - is the command Jon posted not working? If so then we need to fix it as a bug. Otherwise it's essentially the same command you were wanting at the beginning of this thread, scoped by a particular namespace. If you want to clear up any state on that node you should still be able to do `mesh send <host> clear all`.

FWIW it works for me. See below - I start 11 VMs on two hosts, then tell a specific VM to kill VMs using `mesh send`.

```
minimega[minimega]$ mesh list
ccc64.40g: ccc64.40g
 |--ccc65.40g
ccc65.40g
 |--ccc64.40g
minimega[foo]$ vm launch kvm bar[0-10]
minimega[foo]$ .columns host,name vm info
host      | hostname | name
ccc64.40g | N/A      | bar1
ccc64.40g | N/A      | bar3
ccc64.40g | N/A      | bar5
ccc64.40g | N/A      | bar7
ccc64.40g | N/A      | bar9
ccc65.40g | N/A      | bar0
ccc65.40g | N/A      | bar10
ccc65.40g | N/A      | bar2
ccc65.40g | N/A      | bar4
ccc65.40g | N/A      | bar6
ccc65.40g | N/A      | bar8
minimega[foo]$ mesh send ccc65.40g namespace foo vm kill all
minimega[foo]$ .columns host,name,state vm info
host      | hostname | name  | state
ccc64.40g | N/A      | bar1  | BUILDING
ccc64.40g | N/A      | bar3  | BUILDING
ccc64.40g | N/A      | bar5  | BUILDING
ccc64.40g | N/A      | bar7  | BUILDING
ccc64.40g | N/A      | bar9  | BUILDING
ccc65.40g | N/A      | bar0  | QUIT
ccc65.40g | N/A      | bar10 | QUIT
ccc65.40g | N/A      | bar2  | QUIT
ccc65.40g | N/A      | bar4  | QUIT
ccc65.40g | N/A      | bar6  | QUIT
ccc65.40g | N/A      | bar8  | QUIT
```

**Comment by mkunz7** [comment]
So I was incorrectly assuming namespaces would get distributed when ```ns add-hosts``` is called. 

```
servera mini$ ns add-hosts serverb
```
which would in turn silently run
```
serverb mini$ ns add-hosts servera
```

which is how I understand ```mesh dial``` to work.

You can call ```mesh send server vm kill all``` without killing the whole mesh.

This answers some questions, but is there some technical reason why we are blocking ```mesh send server vm launch```? I was assuming it was because in the case of ```mesh send all vm launch``` it would loop ```vm launch``` n number of times, but if the namespaces don't distribute that's not the case.

**Comment by jcrussell** [comment]
The `vm config` commands don't get broadcast out to all the hosts in the namespace -- the head node collects all the configs and then packages them up to send to the remote hosts on `vm launch`. There's a lot of weirdness that can happen with each `vm config` being broadcast -- what if you set a disk and then add a host to the namespace? Should the new node have `vm config disk` set to the same thing as the rest? It's also much slower to broadcast and get an ACK from all the nodes in the namespace.

**Comment by mkunz7** [comment]
State in that case should be a user problem imo. I'm gonna take your word it gets slow packaging and transferring vm configs. 

Can you tailor scheduling to prioritize memory over cpu? For example if I have a mesh of 32 core servers with 128gb of ram and 256gb of ram. I don't want to launch more than 64 2gb vms on the 128gb ram servers, but the 256gb ram servers can handle it just fine.

Also I've been writing my launch scripts to use ```vm config schedule``` for each server but I've found it takes about 15 seconds to issue the commands per server. On 25 servers what used to take seconds to boot now takes 6min. ```vm config schedule``` doesn't support wildcarding and if you do a variety of things break if you ```clear vm config schedule```.

**Comment by jcrussell** [comment]
See [Launching VMs](https://tip.minimega.org/articles/namespaces.article#TOC_2.4.) for info about queueing which batches launching and [Scheduler](https://tip.minimega.org/articles/namespaces.article#TOC_2.5.) for info about tweaking the scheduler to place VMs based on committed memory.

**Comment by mkunz7** [comment]
Is there a way to set a max over commit for cpu and memory?

For example I have three servers totaling 120 cores.
```
ServerA 32 core 256 gB
ServerB 40 core 128 gB
ServerC 48 core 512 gB
```
For performance reasons, I don't want to run more than 2 virtual cores per actual hardware core or more virtual memory than physically available. If I ```ns load memcommit``` and launch a bunch of vms. It evenly distributes via percentage of memory used, but I'll way over commit cpu on ServerA and ServerC.

**Comment by jcrussell** [comment]
Not currently. Open a feature request.
