### ISSUE TITLE
bug: minimega -e

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1279]
**Environment**
1. minimega version: master
2. Linux distro/version: Ubuntu 16.04
3. Go compiler version: 1.11.2
4. VM types: all

**Description**
minimega -e wont allow a command that is string quoted argument

**To Reproduce**
```minimega -e file list``` works
```minimega -e 'file list'``` does not

**Expected behavior**
previous versions allowed me to pass a string quoted argument

**Comment by jcrussell** [comment]
I can change it so that if there's only one argument, it will treat the argument as the whole command. If there's more than one argument, it will return an error (i.e. `minimega -e "mesh send" all host` is not a valid command).

**Comment by mkunz7** [comment]
I'm ok with that constraint. Make sure single quoting still works ie ```minimega -e "shell echo 'hello'"```
