### ISSUE TITLE
vmconfiger: broken with new versions of Go?

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1283]
**Describe your environment**

1. minimega version: master
2. Linux distro/version: N/A
3. Go compiler version: 1.10.x and 1.11.x
4. VM types: N/A

**Describe the bug**

`go generate minimega` fails with an error that it is unable to import one of the vendored dependencies.

**To Reproduce**

```bash
source env.bash
go install vmconfiger
go generate minimega
```

**Expected behavior**

Output new `vmconfig_cli.go`.

**Comment by jcrussell** [comment]
With go1.12:

```
$ go generate minimega
FATAL vmconfiger.go:63: checking package: proc.go:11:7: could not import github.com/c9s/goprocinfo/linux (can't find import: "vendor/github.com/c9s/goprocinfo/linux")
src/minimega/vmconfig.go:5: running "../../bin/vmconfiger": exit status 1
```

**Comment by djfritz** [comment]
@jcrussell status?

**Comment by jcrussell** [comment]
I'm not sure. Combination of monorepo + vendoring makes this a hard one to figure out.

**Comment by jcrussell** [comment]
We can probably push this to v2.7 since it's non-critical.
