### ISSUE TITLE
minimega: sanitize namespace names

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1288]
**Describe your environment**

1. minimega version: master
2. Linux distro/version: N/A
3. Go compiler version: N/A
4. VM types: N/A

**Describe the bug**

`../../foo` is an allowable namespace and probably shouldn't be since we use the namespace to form filepaths. Only allow ascii-numeric-hyphen-underscores?
 
**To Reproduce**

```
namespace ../../foo
shell ls /tmp/foo
```

**Expected behavior**

Invalid namespace, try again.

**Comment by djfritz** [comment]
Agreed - definitely sensible to avoid namespace foo'); drop table ...
