### ISSUE TITLE
minimega: add `vm net add/remove`

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1290]
Extend the `vm net` API to add/remove interfaces using QMP commands.

**Comment by djfritz** [comment]
Why do we need this? Hotplugging PCI devices can do all sorts of weird things, especially to windows VMs. Do we need this for 2.6? 

@jcrussell

**Comment by djfritz** [comment]
Roger - do we need this for 2.6 then?

**Comment by csymonds** [comment]
Yes. My goal is to have this one done within a week.

**Comment by mkunz7** [comment]
Might be worth looking into hotplugging usb-net devices.

**Comment by djfritz** [comment]
Kicking this to 2.7

**Comment by csymonds** [comment]
Note: net add will be part of 2.7 release, net remove likely in 2.8
