### ISSUE TITLE
ranges: split on "."

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1299]
`ranges` could split on "." so that we can collapse hostnames with a common domain. Right now ["foo1.eth", "foo2.eth"] would not be collapsed into "foo[1-2].eth".

**Comment by djfritz** [comment]
Agreed... HOWEVER - hostnames shouldn't be named like this </rant>

I wouldn't be at all surprised to hear that this naming scheme for hostnames came from the whole vlan suffix thing for interfaces - eth2.101, etc. That was so untenable that udev stepped in and started just renaming interfaces to sane things... until systemd ate udev. 

At any rate, this seems fine to me - however why not ditch the notion of splitting on . and just make this generic, allowing numeric expansions anywhere:

`foo[1-2]bar[6-7]`

**Comment by jcrussell** [comment]
#1327
