### ISSUE TITLE
bug: snapshot false unable to launch

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1300]
**Describe your environment**

1. minimega version l- atest
2. Linux distro/version - ubuntu 16.04
3. Go compiler version - 1.10.2
4. VM types - kvm

**Describe the bug**
Launching with snapshot false errors

```
/A        | N/A      | N/A  | N/A     | N/A  | N/A    | N/A          | {"error":"qemu killed: exit status 1 QEMU waiting for connection on: disconnected:unix:/tmp/minimega/4/qmp,server\nqemu-system-x86_64: -drive file=/tmp/minimega/3/disk-0.qcow2,media=disk,if=ide,cache=writeback: Could not open '/tmp/minimega/3/disk-0.qcow2': No such file or directory\n"}
```

**To Reproduce**
```
vm config disk /mnt/storage/disk.qcow2
vm config snapshot false
vm launch kvm a
vm start a
```

**Expected behavior**
Vm launches without error

**Comment by djfritz** [comment]
I’m guessing a regression from #1284

@jasoncontrib I wonder if we’ve introduced an order of operations issue
here. We have tests that look at snapshot flags in the pr above, but not
looking at setting the snapshot mode after the disk.

@mkunz7 can you test again setting the snapshot mode first. If it clears up
then that helps narrow down the bug.

**Comment by djfritz** [comment]
Actually on a second look the updated tests don’t actually launch any VMs
so it’s possible snapshot false is broken no matter what.

https://github.com/jcrussell/minimega/blob/f27eb1768f5a3e34aa4c41f3ac8102f0e33b1dee/tests/diskconfig

**Comment by mkunz7** [comment]
I dug around some more, looks like there's a little more to it, the bug only happens following a vm config clone. 

```
vm config disk test.qcow2
vm launch kvm test
vm start test
vm config clone test
vm kill test
vm flush
vm config snapshot false
vm launch kvm newtest
vm start newtest
```

**Comment by djfritz** [comment]
The SnapshotPath part of the array of disk paths may be getting copied over
now.

@jasoncontrib can we add Kunz’s case to the tests along with whatever fix.

**Comment by jasoncontrib** [comment]
@mkunz7 Thanks for digging into it, does PR #1302 fix this issue for you?

**Comment by mkunz7** [comment]
1. It does for my above case. 

2. Can we print this test cases error to mini's cli?
```
vm config disk test.qcow2
vm config snapshot false
vm launch kvm a
vm config snapshot true
vm launch kvm b
```
with debug logging on and saving to a file you see 
```
2019/04/04 17:40:03 ERROR namespace.go:443: launch error, host server -- disk conflict with vm a: /data/mmfiles/test.qcow2
```

3. The disk path is missing from miniweb with the snapshot change. 

4. Has anyone tested initrd/kernel pairings with snapshot true with this change? Looking at qemu-override it doesn't appear to be doing anything different from snapshot true and snapshot false.

5. This is a weird one that works and shouldn't.

```
vm config disk test.qcow2 test.qcow2
vm config snapshot false
vm launch kvm test
vm start test
```

**Comment by jasoncontrib** [comment]
1. Great

2. Maybe I'm misunderstanding what you mean, but I do see that error showing up on minimega's CLI, with the default logging level and arguments (just `sudo bin/minimega`). Was there some other / additional logging behavior you were expecting?

3. We can fix that. Would it be useful to see the path to the temporary snapshot disk image that is created as well (in case you wanted to save it off), or is that unnecessary?

4. and 5. maintain the same behavior as before the snapshot merge, but we may want to do something about it. @djfritz @jcrussell ?

**Comment by mkunz7** [comment]
2. I don't think I'm doing anything magic and I'm not seeing errors when I should
![test2](https://user-images.githubusercontent.com/5001991/55609453-56607500-5746-11e9-9db9-fe93807da92d.PNG)

3. might as well show it if you ask me

4. learn something new everyday

**Comment by djfritz** [comment]
4. If you're combining kernel/initrd and disk AND twiddling the snapshot flag, we should see the correct behavior (same as if you weren't using kernel/initrd). This way you can boot from a kernel/initrd and still mount a RO or RW disk. Is this functioning correctly?

5. I agree with Kunz, this shouldn't work - we probably just shouldn't allow using the same disk twice in a single VM regardless - I see no use case for this. If we want to be less draconian we can just warn/error on this the same way we do with snapshot=false across VMs.

**Comment by mkunz7** [comment]
4. Didn’t test
5. Less draconian please

**Comment by jasoncontrib** [comment]
@mkunz7 2. That is puzzling, here's what I get, as expected:
![disk_conflict_error](https://user-images.githubusercontent.com/22775345/55748698-2a6a1b80-59f4-11e9-8861-5582f1dc1ab5.png)

What's your command-line for invoking minimega?

**Comment by mkunz7** [comment]
It’s probably because I run mini in a tmux and do a mini attach

**Comment by djfritz** [comment]
Yea there's a larger issue/need to make sure log data, at any level, is routed to the right places, including -attach and other interfaces. I suspect there's an easy fix embedded in there somewhere...
