### ISSUE TITLE
miniweb: top/info view links not working

### ISSUE THREAD

**Issue by csymonds** [sandia-minimega/minimega#1306]
**Describe your environment**

1. minimega version  8f2b17751b70045aa20a77cb83b9e25a1c4d5b34 2019-04-03
2. firefox 60.6.1esr (32-bit)

Toggle info view/Toggle top view links on /vms not properly loading the respective views.
Manually entering the respective urls and reloading the page will get them to load, but clicking the link does not work.

**To Reproduce**
1. Go to miniweb/vms
2. Click on 'Toggle top view' link
3. Page reloads the same view without switching. URL does not update properly.

**Expected behavior**
Page reload to the respective view clicked, new url /vms#top

**Comment by jcrussell** [comment]
Seems to work in Chrome.

**Comment by djfritz** [comment]
@csymonds status on this?

**Comment by csymonds** [comment]
@djfritz it's on my todo list. The goal is to clear for 2.6

**Comment by jcrussell** [comment]
@csymonds: any updates?

**Comment by djfritz** [comment]
fixed by #1364
