### ISSUE TITLE
Feature Request: ns add-hosts autocompletion

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1308]
It would be nice if ns add-hosts polled ```mesh list``` for auto complete allowing for ```ns add-hosts \t``` and ```ns add-hosts all```

It would also be really nice if there was a ```mesh print``` where it didn't print adjacent neighbors just a list of the members in the mesh.

```
$ mesh print
apple[1-5],apple7,oranges[2-10],oranges20
```

**Comment by jcrussell** [comment]
`ns add-hosts all` should work. Tabbed completion wouldn't be hard to add.

Could add `mesh list peers` or do you think it should include the local node?

**Comment by mkunz7** [comment]
Hey what do you know all does work :) ```vm config schedule \t``` should be a thing too. 

It would make sense to me to include the local node. Maybe a ```mesh list members```

**Comment by jcrussell** [comment]
This is the problem with adding some tab completion, soon people expect it everywhere :P

**Comment by jcrussell** [comment]
`mesh list peers` and `mesh list all` could both be useful.
