### ISSUE TITLE
tests: fix plumbing_basic

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1313]
**Describe your environment**

1. minimega version: master

**Describe the bug**

Even the commands are off:
```
diff plumbing_basic.got plumbing_basic.want
## .columns name,mode,readers,writers,count pipe              | ## pipe
```

**Comment by djfritz** [comment]
Best I can tell this is just a test that we forgot to update. Output is sane but there are new columns:

      21,29c21,29
     < ## .columns name,mode,readers,writers,count pipe
     < name         | mode | readers | writers | count
     < minimega//p0 | all  | 2       | 0       | 0
     < minimega//p1 | all  | 2       | 1       | 0
     < minimega//p2 | all  | 2       | 1       | 0
     < minimega//p3 | all  | 0       | 1       | 0
     < minimega//p4 | all  | 0       | 1       | 0
     < minimega//p5 | all  | 0       | 1       | 0
     < minimega//p6 | all  | 0       | 1       | 0
     ---
     > ## pipe
     > name         | mode | readers | writers | count | via | previous
     > minimega//p0 | all  | 2       | 0       | 0     |     | 
     > minimega//p1 | all  | 2       | 1       | 0     |     | 
     > minimega//p2 | all  | 2       | 1       | 0     |     | 
     > minimega//p3 | all  | 0       | 1       | 0     |     | 
     > minimega//p4 | all  | 0       | 1       | 0     |     | 
     > minimega//p5 | all  | 0       | 1       | 0     |     | 
     > minimega//p6 | all  | 0       | 1       | 0     |     |
     34,42c34,42
     < ## .columns name,mode,readers,writers,count pipe
     < name         | mode | readers | writers | count
     < minimega//p0 | all  | 2       | 0       | 1
     < minimega//p1 | all  | 2       | 1       | 1
     < minimega//p2 | all  | 2       | 1       | 1
     < minimega//p3 | all  | 0       | 1       | 1
     < minimega//p4 | all  | 0       | 1       | 1
     < minimega//p5 | all  | 0       | 1       | 1
     < minimega//p6 | all  | 0       | 1       | 1
     ---
     > ## pipe
     > name         | mode | readers | writers | count | via | previous
     > minimega//p0 | all  | 2       | 0       | 1     |     | Hello to you.
     > minimega//p1 | all  | 2       | 1       | 1     |     | Hello to you.
     > minimega//p2 | all  | 2       | 1       | 1     |     | Hello to you.
     > minimega//p3 | all  | 0       | 1       | 1     |     | Hello to you.
     > minimega//p4 | all  | 0       | 1       | 1     |     | Hello to you.
     > minimega//p5 | all  | 0       | 1       | 1     |     | Hello to you.
     > minimega//p6 | all  | 0       | 1       | 1     |     | Hello to you.
     54,62c54,62
     < ## .columns name,mode,readers,writers,count pipe
     < name         | mode        | readers | writers | count
     < minimega//p0 | round-robin | 2       | 0       | 5
     < minimega//p1 | round-robin | 2       | 1       | 3
     < minimega//p2 | round-robin | 2       | 1       | 3
     < minimega//p3 | all         | 0       | 1       | 2
     < minimega//p4 | all         | 0       | 1       | 2
     < minimega//p5 | all         | 0       | 1       | 2
     < minimega//p6 | all         | 0       | 1       | 2
     ---
     > ## pipe
     > name         | mode        | readers | writers | count | via | previous
     > minimega//p0 | round-robin | 2       | 0       | 5     |     | This is round 4.
     > minimega//p1 | round-robin | 2       | 1       | 3     |     | This is round 4.
     > minimega//p2 | round-robin | 2       | 1       | 3     |     | This is round 3.
     > minimega//p3 | all         | 0       | 1       | 2     |     | This is round 2.
     > minimega//p4 | all         | 0       | 1       | 2     |     | This is round 4.
     > minimega//p5 | all         | 0       | 1       | 2     |     | This is round 3.
     > minimega//p6 | all         | 0       | 1       | 2     |     | This is round robin.

**Comment by djfritz** [comment]
@jcrussell am I doing something wrong here? Why is minitest nagging that the output doesn't match?

     $ bin/minitest -run plumbing_basic                    
     got != want for plumbing_basic
     $ md5sum tests/plumbing_basic.*
     552a7fde951f8fff4a408b0f433f7407  tests/plumbing_basic.got
     552a7fde951f8fff4a408b0f433f7407  tests/plumbing_basic.want
     $ diff tests/plumbing_basic.*
     $

**Comment by jcrussell** [comment]
I think it's complaining about `distributed/plumbing_basic`.

All the `miniccc`-dependent tests seem to be broken but haven't been able to find time to investigate.
