### ISSUE TITLE
minimega/miniweb: `file stream` is problematic

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1323]
**Describe your environment**

1. minimega version: master
2. Linux distro/version: N/A
3. Go compiler version: N/A
4. VM types: N/A

**Describe the bug**

Streaming a large file to a remote user locks up minimega because the `file stream` blocks until the file is fully streamed. Would be nice if the streaming happened in the background.

**To Reproduce**
1. Add large file to `/tmp/minimega/files/`
2. Download via `miniweb`
3. Try to run command in minimega

**Expected behavior**
Continue to use minimega while file is streamed in the background.

**Comment by jacdavi** [comment]
This should have been fixed in #1475
