### ISSUE TITLE
minimega: clogged containers

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1336]
**Describe your environment**

1. minimega version: master
2. Linux distro/version: debian testing
3. Go compiler version: N/A
4. VM types: container

**Describe the bug**

Getting this error message on flush:

```ERROR vms.go:359: clogged vm 1: remove /tmp/minimega/namespaces/minimega/b03c6f48-71c5-4169-82c4-5749d0f8efa3: no such file or directory```

Possibly related to #1287.

**To Reproduce**

```
vm config filesystem /path/to/filesystem
vm launch container 1
vm kill all
vm flush
```

**Expected behavior**

No error message. Doesn't seem to be polluting filesystem though.

**Comment by djfritz** [comment]
This is #1287. It looks like that PR didn't add VM alias paths to containers, only kvm instances - so the base vm Flush() fails because the symlink never existed. @jasoncontrib @jcrussell
