### ISSUE TITLE
bug: cc rtunnel is not working

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#1384]
**Describe your environment**

1. minimega version
latest
2. Linux distro/version
ubuntu 18.04.3 desktop
3. Go compiler version
1.12.13
4. VM types
kvm

**Describe the bug**
Reverse tunnels error with vm not found and are not created. 

**To Reproduce**
Start minimega
Start miniccc on a vm over serial
cc rtunnel 1234 localhost 80

**Expected behavior**
reverse tunnel should be made

**Comment by djfritz** [comment]
This was broken by me a few months ago with a VM name check happening too early - fix incoming.
