### ISSUE TITLE
New GUI

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#140]
See summary - Much work has been done on a new web interface, as shown in the gui branch. Finish, polish, and merge to master.

**Comment by floren** [comment]
TESTING
?       apigen  [no test files]
?       gonetflow       [no test files]
?       gopcap  [no test files]
--- FAIL: TestDecodeRawRGB (0.00s)
        reader_test.go:89: open testdata/test_rgb_raw.ppm: no such file or directory
FAIL
FAIL    gopnm   0.002s

**Comment by djfritz** [comment]
failed tests are fixed with:

https://github.com/sandia-minimega/minimega/commit/eb62ea83f2052a612608965c4e8c670e3142a366

Please pull from master.

**Comment by djfritz** [comment]
fixed by https://github.com/sandia-minimega/minimega/issues/156
