### ISSUE TITLE
igor: add console

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#1400]
`ipmitool` has a console that igor could proxy so that users can diagnose boot issues.

From `man ipmitool`:

activate
Causes ipmitool to enter Intel IPMI v1.5 Serial Over LAN mode. An RMCP+ connection is made to the BMC, the terminal is set to raw mode, and user input is sent to the serial console on the remote server. On exit, the the SOL payload mode is deactivated and the terminal is reset to its original settings.

**Comment by afbagwell** [comment]
In version 2.x of igor we are moving to a client-server architecture. Users will not be logging into or necessarily even have an account on the cluster head node. Thus connecting to console apps on the head node is not in the purview of igor at this time.
