### ISSUE TITLE
unit tests

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#141]
There are glaring omissions in our unit tests. This needs significant investment. Some things cannot be tested well with the available unit test framework in Go, so there is another ticket for runtime testing. For things that can be well tested though, we need a lot of help.

**Comment by jcrussell** [comment]
Agreed. Started adding some tests for `vm config ...` to ticket-86 branch.

**Comment by djfritz** [comment]
Closing as this ticket is way too generic. We should add tickets to add specific tests.
