### ISSUE TITLE
[miniccc] Access denied to \\.\Global\cc serial port on Windows 10 

### ISSUE THREAD

**Issue by activeshadow** [sandia-minimega/minimega#1418]
Has anyone else seen this and had any luck overcoming it? I get an Access Denied error in the logs from [line 183](https://github.com/sandia-minimega/minimega/blob/50f959ee87423ae6d39d08f2094cc48f09bcaa0a/src/miniccc/main.go#L183). I have confirmed that the VirtIO Serial driver is installed in the Windows 10 VM.

I'm running `miniccc` as `SYSTEM` on boot, so I'm assuming it's not a permissions issue. Perhaps something else is connected to the serial port? That or maybe `miniccc` needs to be whitelisted.

I've confirmed this same setup works just fine in a Windows Server 2008 R2 VM.

**Comment by mkunz7** [comment]
Works fine for me https://ku.nz/miniclass/module11.html make sure your miniccc binary is the same version the server is running

![miniccc2](https://user-images.githubusercontent.com/5001991/83668297-53a12000-a595-11ea-8edd-b8967ef5df18.PNG)
![miniccc](https://user-images.githubusercontent.com/5001991/83668298-5439b680-a595-11ea-8ca0-0f9af7f71a7e.PNG)

**Comment by activeshadow** [comment]
Thanks @mkunz7 for going the extra mile and verifying! I'll do some additional testing and report back here. More to come.

**Comment by activeshadow** [comment]
OK, after testing again with an updated copy of `miniccc.exe`, I no longer see the `Access denied` issue and am showing `cc_active = true` for the Windows 10 VM.

Thanks again @mkunz7 and sorry for taking up some of your time to verify this!
