### ISSUE TITLE
runtime test framework

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#142]
A number of components in minimega cannot be tested with Go's unit test framework, in particular interactions with qemu/qmp, etc. We need a runtime test harness to run on a small cluster. The framework can be fairly simple - support some language and minimega scripts for runtime tests, and support some sort of success assertion.

Beyond that, we need to write the runtime tests we know we'll need, and scope a development practice in the 'contributing.article' for adding new tests.

Good intern project.

**Comment by djfritz** [comment]
@jcrussell The framework exists now right? Now we just need to add more tests?

**Comment by jcrussell** [comment]
It does exist but there are a number of improvements that should be made. I'm fine with closing this ticket and creating individual tickets for each of the desired improvements.

**Comment by djfritz** [comment]
In that case...
