### ISSUE TITLE
minimega: default gui/web paths

### ISSUE THREAD

**Issue by floren** [sandia-minimega/minimega#144]
"web" needed the path to novnc. We defaulted to $pwd/misc/novnc.

"gui" needs novnc, d3, and presumably eventually a javascript terminal. It defaults those to /opt/minimega/misc/[novnc,d3]

I've generally held that $pwd/misc/novnc is a decent start because less experienced users will probably be running "./bin/minimega" from the root of the repo, while more advanced/dedicated users who have created /opt/minimega can be expected to change paths themselves if they need.

Jeremy suggested an "env" command, which we could just use to set $CWD, or we could set a "webroot" variable which is used as the root for novnc, d3, and other web junk we need.

**Comment by bjwrigh** [comment]
I can go for the "env" command.  I plan to overtake the 'web' code soon, as
well as co-locate novnc and web things (if nobody opposes either) along
with some of my code review and overhaul as I roll it into master.

**Comment by floren** [comment]
The GUI looks really good, so I'd like to bring it into master ASAP.

Here's what I propose as a simple way to bring in "gui":

* Move misc/novnc and misc/d3 into misc/web
* Change "gui" command to take a webroot argument, so you say "gui webroot /opt/minimega/misc/web"
* Make default webroot $CWD/misc/web
* Remove old "web" code, rename "gui" to "web".

Advantages:

* Less configuration needed
* Default webroot helps newbies who are probably running from inside the minimega dir

**Comment by djfritz** [comment]
Let's put up a pull request for this.

For the environment - the default http.Transport registers paths with Handler() and HandlerFunc(), but doesn't have a facility to change those paths once you start the webserver. That stinks if you accidentally put the wrong path in, or use the default and the files aren't there. You either have to restart minimega or move/link files.

Can we add a custom http.Transport or whatever other interface is needed to make the paths mutable at runtime?

**Comment by djfritz** [comment]
Is this done in the new web pull request?

**Comment by djfritz** [comment]
fixed by https://github.com/sandia-minimega/minimega/issues/156
