### ISSUE TITLE
While following the tutorial example, "vm launch kvm test" is not working

### ISSUE THREAD

**Issue by sahabulh** [sandia-minimega/minimega#1468]
Using prebuilt [minimega-2.7.tar.bz2](https://storage.googleapis.com/minimega-files/minimega-2.7.tar.bz2) on Ubuntu 20.04 (installed on VirtualBox). I followed the instruction [here](https://minimega.org/articles/tutorials/quickstart.article). When I try to launch the test VM, I get the following error:

```
2022/04/20 14:17:36 ERROR vm.go:744: vm 0: unable to connect to qmp socket: qmp timeout
2022/04/20 14:17:36 ERROR vm.go:744: vm 0: qemu killed: exit status 1 qemu-system-x86_64: -qmp unix:/tmp/minimega/0/qmp,server: info: QEMU waiting for connection on: disconnected:unix:/tmp/minimega/0/qmp,server
Could not access KVM kernel module: No such file or directory
qemu-system-x86_64: failed to initialize KVM: No such file or directory

2022/04/20 14:17:36 ERROR namespace.go:453: launch error, host sahabul -- unable to connect to qmp socket: qmp timeout
```

**Comment by mdp3x** [comment]
You need to enable features for nested virtualization. I bet if you run these commands they'll error.
```
modprobe kvm
modprobe kvm_intel
```
https://docs.fedoraproject.org/en-US/quick-docs/using-nested-virtualization-in-kvm/
try: https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html

On vmware workstation you just need to check the box to virtualize intel vt-x/amd-v

**Comment by jacdavi** [comment]
@sahabulh I'm going to go ahead and close this as there haven't been any updates. Feel free to reopen or create a new issue if needed!
