### ISSUE TITLE
docs: website syncronization with current release

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#154]
Our website and repo infrastructure is very similar to golang. We leave the bleeding edge on master, and docs are built from that. Currently the website is generated from master hourly. 

When we release 2.0 and future releases, minimega.org should give the docs for the current release, and we should add something like head.minimega.org for the latest.

Thoughts?

**Comment by djfritz** [comment]
This will probably just involve making the hourly builder push to head.minimega.org, and the main site done by hand (since it updates only on release cycles).

**Comment by jcrussell** [comment]
http://tip.golang.org/ is the URL for the latest go docs, perhaps
http://tip.minimega.org? Otherwise, LGTM.

**Comment by floren** [comment]
http://tip.minimega.org now points to the latest go docs, which should be updated hourly
http://minimega.org will contain docs for the current release.
