### ISSUE TITLE
VM net disconnect does not update MM data

### ISSUE THREAD

**Issue by bjwrigh** [sandia-minimega/minimega#184]
vm net disconnect 0 0 
vm info
(see that the interface still reports that the 0'th interface is still connected on the bridge,vlan,w/ mac, etc)

fritz has seen the bug if this isnt enough information to reproduce the bug

**Comment by djfritz** [comment]
This is a bug, and should be fixed as a side effect with @jcrussell 's new VM interface implementation.

**Comment by jcrussell** [comment]
@bjwrigh: Think this is fixed, see below. Can you confirm?

```
minimega$ vm config net 0
minimega$ vm launch kvm 1
minimega$ vm info
host     | id | name | state    | memory | vcpus | type | vlan | bridge        | tap         | mac                 | ip | ip6 | bandwidth | tags
foo | 0  | vm-0 | BUILDING | 2048   | 1     | kvm  | [0]  | [mega_bridge] | [mega_tap0] | [00:16:b4:2f:e3:2c] | [] | []  | [N/A]     | map[]
minimega$ vm net disconnect 0 0
minimega$ vm info
host     | id | name | state    | memory | vcpus | type | vlan           | bridge        | tap         | mac                 | ip | ip6 | bandwidth | tags
foo | 0  | vm-0 | BUILDING | 2048   | 1     | kvm  | [disconnected] | [mega_bridge] | [mega_tap0] | [00:16:b4:2f:e3:2c] | [] | []  | [0.0/0.0] | map[]
```

**Comment by djfritz** [comment]
@bjwrigh ping

**Comment by bjwrigh** [comment]
The fix looks good, however, I'd like to pose a question...

The vlan shows disconnected, but the bridge, tap, mac, ip, bandwidth all show previous values.

While I believe the tap, mac, (ip is residual) should all remain, as they won't change...

The others might be misleading...

thoughts?

@djfritz 
@jcrussell

**Comment by jcrussell** [comment]
The bandwidth should go away on the next "refresh" interval which is currently every 5 seconds.

I'm not sure if it makes sense to mess with the other fields or not -- @djfritz, what do you think?

**Comment by djfritz** [comment]
IP and bandwidth will change dynamically as @jcrussell points out. MAC is static, along with the tap name, so we shouldn't mess with those.

The bridge and vlan should be updated or marked "disconnected" when using the `vm netmod` API. Currently it's just VLAN? If that's the case, let's change it to also update the bridge field.

@jcrussell @bjwrigh

**Comment by jcrussell** [comment]
Have last patch for this, will push when I have access to my SSH keys.
