### ISSUE TITLE
Feature request: vm reset

### ISSUE THREAD

**Issue by bjwrigh** [sandia-minimega/minimega#185]
Not sure if this ever got done...or put as a feature request...

'vm reset vm-0' 
    -would take vm-0 back to original state from which it was started  
    -essentially grouping 'vm kill vm-0;vm start vm-0'.
    -would be useful on multiple vm's to be reset at once.  i.e. to put an environment back to a freshly booted environment for training.

**Comment by djfritz** [comment]
this is done already with vm kill + vm start, and would break the flimsy goal of API orthogonality we have. The vm start semantics did change in https://github.com/sandia-minimega/minimega/commit/efea962be09f0a53e16afc729ce209fb8bc1d487 by allowing restarts of ERROR state VMs

**Comment by bjwrigh** [comment]
The two command set does not allow for multiple vm 'resets' to be done
without manually scripting a whole lot of things for a quick hack to be
done.   The main reason i wanted the feature is to do something like:  vm
reset 23,60-66,78 and have those cycle.

@djfritz
