### ISSUE TITLE
Feature (that could fix a bug):  vm tag all {key} {value}

### ISSUE THREAD

**Issue by bjwrigh** [sandia-minimega/minimega#191]
'mesh send all vm tag all time_started aug5_22:01'

add functionality of grouping / all to vm tag to allow the same tags to be added to multiple vms simultaneously.

**Comment by bjwrigh** [comment]
the bug might've been attributed to kvmi things...assume no problem unless updated.

**Comment by jcrussell** [comment]
This is pretty easy to implement. We could add the following patterns to vm tag:

vm tag <vm id or name or all> <key or all>
vm tag <vm id or name or all> <key> [value]

The first would allow you to get a table with rows: vm name, key, value. You could then filter this if needed.

The second does what the ticket describes.

@djfritz  -- [Y/n]?

**Comment by djfritz** [comment]
Is it more consistent to keep the current "vm tag <name or id> <key> [value]" syntax and add a wildcard check to the name/id field?

**Comment by jcrussell** [comment]
Updated comment.. angle brackets were filtered. Does that change your comment?

**Comment by djfritz** [comment]
Ahh yes, you and I had the same idea. This looks good.

**Comment by jcrussell** [comment]
Closing, fixed in #208.
