### ISSUE TITLE
Bug: nuke

### ISSUE THREAD

**Issue by bjwrigh** [sandia-minimega/minimega#195]
nuke seems to run properly, but does not exit the CLI - and thus hangs.

(for the record, i did a nuke to clean up everything that happened with the previous request (minimega recovery)

**Comment by djfritz** [comment]
This is because runCommand()  https://github.com/sandia-minimega/minimega/blob/master/src/minimega/cli.go#L303

Is only logging the error on the closed connection/failure to encode JSON, where it should be log.Fatal(). Fixing.
