### ISSUE TITLE
minimega: python bindings send() not checking More boolean

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#197]
Responses as defined in the localResponse struct, https://github.com/sandia-minimega/minimega/blob/master/src/minimega/cli.go#L52, Contain a More boolean that indicates to the client that it should continue reading for more responses. The expected behavior is that each localResponse should be rendered/printed upon receiving, and if the More field is set, read more data. This allows for things like the streaming responses that are printed when issuing a 'read' command. 

Currently only 'read' uses More, but the behavior should be future proofed by operating in send()

@devinc 

See https://github.com/sandia-minimega/minimega/blob/master/src/minimega/cli.go#L303 for the implementation of handling More with -attach and -e

**Comment by devinc** [comment]
Should the commands block until all responses are received, then return a single array containing all responses? If so, I have a pull request ready.
