### ISSUE TITLE
minimega: panic in bridge code

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#198]
This one is ugly - either a race from something else calling TapRemove() (such as minimega quitting), or there is a code path that doesn't correctly populate the bridge/lan/tap maps for an added tap. We need a mostly repeatable minimega script to hunt this down @bjwrigh 

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal 0xb code=0x1 addr=0x0 pc=0x40f28f]

    goroutine 419 [running]:
    main.(*bridge).TapRemove(0xc2081d5c20, 0xffffffffffffffff, 0xc208094030, 0xb, 0x0, 0x0)
        /home/fritz/repos/minimega/src/minimega/bridge.go:901 +0xbf
    main.(*bridge).TapDestroy(0xc2081d5c20, 0xffffffffffffffff, 0xc208094030, 0xb, 0x0, 0x0)
        /home/fritz/repos/minimega/src/minimega/bridge.go:695 +0x75
    main.(*vmInfo).launchOne(0xc2081201e0, 0xc2081e2480)
        /home/fritz/repos/minimega/src/minimega/vminfo.go:471 +0x1d08
    created by main.VMs.launch
        /home/fritz/repos/minimega/src/minimega/vmlist.go:242 +0x56f

**Comment by bjwrigh** [comment]
Roger that. i'll try to get something going.  it seems fairly repeatable on
my deployment, but we need it for current testing...so i have to clone the
head node to deploy elsewhere.  probably will borrow the MM cluster.

**Comment by bjwrigh** [comment]
Roger that. i'll try to get something going.  it seems fairly repeatable on
my deployment, but we need it for current testing...so i have to clone the
head node to deploy elsewhere.  probably will borrow the MM cluster.
@djfritz

**Comment by jcrussell** [comment]
I'm working on this. This script causes the panic:

```
vm config net 0
vm launch kvm 1
vm net disconnect 0 0
quit
```
