### ISSUE TITLE
minimega: at least one dangling kvm process on entering VM_ERROR state

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#209]
If you hit the race:

vm launch foo noblock
vm start foo

And get the VM into the error state with the 'qmp not ready' error, you'll notice that qemu for that VM is still running, because vm.start() didn't kill the process after putting it in the error state. Later, vm kill won't attempt to kill it because it's in the error state.

At least two things could happen here instead:

* Attempt to reissue commands on error VMs that aren't actually dead - like 'vm start'. That would require some more book keeping
* Always kill VMs when they enter the error state

**Comment by floren** [comment]
fixed by #211

**Comment by jcrussell** [comment]
Instead, could we have commands that alter a VM's state (e.g. launch/start/kill) acquire the VM's lock field before proceeding? Then, there would be no race -- `vm launch foo noblock` would have to complete before `vm start foo` could proceed. If blocking on `vm start` is not acceptable, we could try to acquire the lock and if it fails, return an error (but not change the VM state).

@djfritz

**Comment by djfritz** [comment]
That's an ideal solution. My VM launch code may not tolerate holding the lock in that big of a block (depending on how much of the launch code/preamble you've rewritten), so it may require a touch of refactoring.

**Comment by jcrussell** [comment]
Playing with this now.

**Comment by djfritz** [comment]
This may be a non-issue with the vm++ branch now merged.

**Comment by jcrussell** [comment]
There's still a race, I think. Going to try to restructure the code to properly lock things to avoid any chance of one.

**Comment by jcrussell** [comment]
Have a patch for this, will test more next week.
