### ISSUE TITLE
minimega: web is SLOW with lots of VMs booted

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#216]
Over a remote/slow connection accessing the web interface is unbearably slow, due to the massive amount of screenshot transfers. It's slow enough that eventually firefox asks if it should continue running the js responsible for loading everything. It *does* eventually finish.

Solutions:

- make the screenshot size even smaller (currently 140px on the long edge)
- don't load screenshots by default, but add a checkbox or something

Thoughts?

**Comment by bjwrigh** [comment]
That's do-able.  Many improvements in the pipeline, I'll add this to the
list.

**Comment by djfritz** [comment]
@jfktrey

**Comment by djfritz** [comment]
Is there a way to only grab the screenshot url on rows we'll be showing? There is some js in there to roll up all of the VMs into pages (default 25 at a time or something). If we could only grab screenshots for those, we'd save a lot of headache...

**Comment by djfritz** [comment]
This appears to be resolved by https://github.com/sandia-minimega/minimega/pull/266

@jfktrey can you comment?

**Comment by jfktrey** [comment]
Yup! Should be solved by the new interface. Images are lazy loaded and updated every ~5 seconds.
