### ISSUE TITLE
minimega: keep internal api calls out of the cli history

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#222]
Currently internal api calls like `vm info` and `vm screenshot` from the web interface get injected into the cli history. That clutters things when you go to do a `write` command after using the web interface.

The internal API calling infrastructure should stay out of the history.

**Comment by jcrussell** [comment]
Ah, the problem is in meshageHandler, record is always set to true. We need to somehow pass the record = false flag through `mesh send <hosts> (cmd)`. We could potentially add a new built-in `.norecord (cmd)` that omits a command from the history -- thoughts?

**Comment by djfritz** [comment]
This gets interesting when you think about future tools that speak to minimega over the unix socket. They aren't sending precompiled commands - just populating the Original field, so the *only* way to convey you don't want to record something in the history is to do something like you suggest.

Let's do it - and make sure it follows the conventions of the other built-ins - stackable, globally settable, etc.

**Comment by jcrussell** [comment]
To keep it consistent with the other built-ins, how about:

```
.record [true,false]
.record <true,false> (command)
```

**Comment by bjwrigh** [comment]
can we make sure this built-in is a per-call only?  that way within the
calls we make internally, we add that, but it does stay persistent?

**Comment by bjwrigh** [comment]
reason for my last comment:  is there a time/reason when you would want to
not record a string of commands?

**Comment by djfritz** [comment]
Patch looks good to me.
