### ISSUE TITLE
minimega: additional option for 'vm screenshot'

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#252]
The `vm screenshot` API has a hardcoded path of `screenshot.png` in a VM's runtime directory. This works well enough until you have an external tool using screenshots while someone is using the web service. The web service grabs screenshots at a small resolution, and this may clobber images needed by external tools. It's in effect a race.

The web service doesn't actually use the image data written to disk - image data is passed in the minicli response itself. This opens up two options:

1. Allow specifying a path for an image, and have the web service point to /dev/null
2. Add an optional arg to the API to not write out an image.

I'm leaning towards 1. Thoughts?

@jcrussell

**Comment by jcrussell** [comment]
I like option 1 as well. However, one small issue with an optional path is then we would have two optional arguments to `vm screenshot` which is a problem for minicli.
