### ISSUE TITLE
Option in api/console to get current namespace

### ISSUE THREAD

**Issue by x64x6a** [sandia-minimega/minimega#254]
As far as my knowledge, the only way to get the namespace is to either remember it, get it from a config file, or get it from process list.
Since I'm using the api, it would be nice to use the api instead of system commands or reading from a file.  

@jcrussell suggested that the issue be posted

**Comment by djfritz** [comment]
What's your use case? namespacing meshage is a somewhat special case. 

If we add this, let's just add it to `mesh status` along with the listening port.

**Comment by x64x6a** [comment]
As of this moment, I would like to use it for debugging purposes.  Perhaps it would be useful if you're running multiple meshes.  I think this should have a low-priority.

**Comment by djfritz** [comment]
'mutiple meshes' is the special use case, and generally should be avoided as a means to accomplish multitenancy. We have an effort to add a proper scheduler that will provide a type of loose multitenancy. 

I'm fine adding this to `mesh status` unless @jcrussell has reservations.
