### ISSUE TITLE
minimega: web reporting a lot of qmp errors

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#273]
2015/08/06 22:20:09 ERROR web.go:170: write unix /tmp/minimega/395/qmp: broken pipe
    2015/08/06 22:20:09 http: multiple response.WriteHeader call

@jcrussell @jfktrey

Can you investigate? If it's not an issue, let's supress this error - there's a LOT of chatter with this error on big experiments.

**Comment by djfritz** [comment]
I'm seeing why - These errors are happening when doing things like 'vm kill all', etc. The web service isn't catching that the VM is going away.

**Comment by jcrussell** [comment]
I have a patch for this. Will push later once I have access to my SSH keys.
