### ISSUE TITLE
minimega: add static configuration support to dnsmasq and vyatta APIs

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#279]
See summary. Add support for specifying static IPs, etc. referenced by MAC, VM, etc. on future dnsmasq and already running dnsmasq instances.

Example:

    dnsmasq static vm <vm id> <ipv4 address/subnet>

**Comment by mkunz7** [comment]
While we are at it, 
Can we get add a dns server field?

dnsmasq static vm <vm id> <ipv4 address/subnet> dns <dnsserver>

Currently I'm doing this via /etc/dnsmasq.conf in my own dnsmasq server:
dhcp-option=option:dns-server,10.0.0.1,10.0.0.11

with IPs set by mac address
dhcp-host=12:00:00:00:00:01,10.0.0.11

I think the ability to add Static DNS Entries would help as well.
ie:
dnsmasq static 10.0.0.1 google.com
(--dhcp-hostsfile=/etc/myhosts)

**Comment by floren** [comment]
I think I see how to add static IPs and static DNS entries on the fly. As for setting the dns-server option, not yet, but it's a start

**Comment by floren** [comment]
You'll generally only run dnsmasq on one machine, but what if you want to set a static IP address for a VM that's running on a different machine?

We could also allow

    dnsmasq static vm <mac addr> <ipv4>

**Comment by jcrussell** [comment]
The `dnsmasq` command is a bit weird -- you can start multiple `dnsmasq` processes and then you should be able to kill/configure them independently. Perhaps we should rewrite the `dnsmasq` API to look something like:

```
dnsmasq
dnsmasq start <interfaces> [config]...
dnsmasq configure <ID> <config,> <config files>...
dnsmasq configure <ID> <dns,> <host> <ip>
dnsmasq configure <ID> <ip,> <mac> <ip>
dnsmasq kill <id or all>
```

the `dnsmasq static vm <vm id> <ipv4 address/subnet>` command seems like it would require too much magic to me -- how would we know which `dnsmasq` to modify and, if the VM has multiple interfaces, which MAC address to use (or would we add an entry for each MAC address)?

**Comment by floren** [comment]
That makes sense, I'll look into that.

**Comment by floren** [comment]
Partially fixed by #353 but no vyatta support yet.

**Comment by djfritz** [comment]
vyatta support will be deprecated with the minirouter rollout (which will have static config support). Can we close this as fixed?

**Comment by djfritz** [comment]
More than two months later, I'm calling that a 'yes'.
