### ISSUE TITLE
minimega: add graph view tag responses

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#293]
The graph view should respond to `vm tag` fields. We'll use this thread to iterate what tags the view should respond to. We'll probably want to isolate the 'graph' tags with a prefix such as:

    graph_color
    graph_text

@jfktrey

**Comment by djfritz** [comment]
@jcrussell @floren 

Can we start iterating tags?

**Comment by floren** [comment]
You mean the web graph view?

**Comment by djfritz** [comment]
Duplicate of #292
