### ISSUE TITLE
minimega: openvswitch grouped operations

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#296]
openvswitch addport/delport operations can be very slow, especially when doing things like "add 5000 taps". It can be made much faster if operations are grouped into single commands. This should be added.

**Comment by jcrussell** [comment]
`delport` is the slow part -- takes minutes to kill thousands of taps.

Idea: mark taps as unneeded and have a separate goroutine go through and clean up unneeded taps in batches.

**Comment by djfritz** [comment]
Providing some data to back this up. Attached are per-vm latencies to do an OVS add-port/del-port operation. This was done with:

    vm config net 100
    vm launch container 250
    vm start all
    vm kill all

The times are recorded from debug logging in cmdTimeout. cmdTimeout simply logs the time it takes to run a given command.

![ovs_latency](https://cloud.githubusercontent.com/assets/4811604/12207570/a2500098-b604-11e5-86c5-cca2a802c57d.png)

As you can see, launching VMs does indeed have an increasing latency, but it's nothing compared to the latency in removing taps.

**Comment by djfritz** [comment]
To add to the above - if you sum the time to remove all 250 taps, the additional overhead in the `vm kill all` command is only a few milliseconds over the ~90 seconds to remove all of the taps. The bottleneck is clearly around ovs.

**Comment by jcrussell** [comment]
@djfritz Thanks for plotting this! Implementing the mark/sweeper approach should really help.

**Comment by djfritz** [comment]
Patch is ready and is actually pretty clean. I had to refactor a few things in kvm.go and container.go to use this correctly.

For comparison, the time to kill a minimega with 250 running containers without this patch:

    root@ccc1:~# time ./minimega -e quit
    
    real    1m8.770s
    user    0m0.028s
    sys     0m0.008s

And again with:

    time ./minimega_reaptaps -e quit
    
    real    0m6.452s
    user    0m0.024s
    sys     0m0.040s
