### ISSUE TITLE
minimega: panic in bridge code

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#299]
Affects: master, 2.1

Running `minitest` twice against a running minimega instance causes a crash:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x409932]

goroutine 942 [running]:
runtime.panic(0xa9e660, 0x108d373)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
main.(*bridge).TapCreate(0xc2085908c0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0)
        src/minimega/bridge.go:670 +0x662
main.(*KvmVM).launch(0xc208616d00, 0xc20816ba40, 0x0, 0x0)
        src/minimega/kvm.go:471 +0x6da
created by main.(*KvmVM).Start
        src/minimega/kvm.go:164 +0x340
```

Might be a race, seeing when there are a large number of existing minimega taps:

```
2015/08/26 22:01:46 WARN bridge.go:1228: tap mega_tap49 already exists, trying again
```

**Comment by djfritz** [comment]
The bridge code is referencing writing to one of the bridge's lan maps.
Every write to that map in the source is wrapped with a lock. There are
reads outside of the lock.

**Comment by jcrussell** [comment]
Observations from starting to refactor the bridge code:

* hostOption appears to be unused -- remove?
* Can we make do without disconnectedTaps? There are a couple of places where locking is a bit more tricky with it (if we don't want to just lock *everything*).
* It doesn't seem like we really need the nested lans/taps in bridges -- there's no code that says "give me all the taps on this VLAN" -- perhaps we should flatten this.
* Is the `bridgeInfo` ouput that's dropped in $minimega/bridges actually useful? It just mirrors the output from the `bridge` command. This may be part of a bigger discussion on how much of minimega's state should be exposed in a proc-like filesystem.

More to come, I'm sure.
