### ISSUE TITLE
Dnsmasq DHCP server not handing out IP addresses

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#316]
Steps to reproduce:

[1] Start minimega
[2] Ensure your networking interface is up

ifconfig p1p1 up

[3] Create a bridge for minimega to use

ovs-vsctl del-br mega_bridge
ovs-vsctl add-br mega_bridge
ovs-vsctl add-port mega_bridge p1p1

[4] Start dnsmasq from the console

tap create 1337 bridge mega_bridge ip 172.16.0.1/24 dhcp_tap
dnsmasq start 172.16.0.1 172.16.0.100 172.168.0.200

[5] Launch some VM's and they wont get dhcp leases

Troubleshooting:
VM's set with static ip addresses can talk to each other
A VM with a static IP address of 172.16.0.22 can ping 172.16.0.1
A tcpdump of 172.16.0.1 (dhcp_tap) shows pings from 172.16.0.22 and various dhcp requests

![dhcp-issues](https://cloud.githubusercontent.com/assets/5001991/9695188/90b7af52-531c-11e5-8ce4-66248a75f01f.PNG)
![dhcptap](https://cloud.githubusercontent.com/assets/5001991/9695189/90b80f10-531c-11e5-8fd8-59edb218416f.PNG)
![dnsmasq running](https://cloud.githubusercontent.com/assets/5001991/9695190/90b9a636-531c-11e5-88ff-2b906717a141.PNG)

**Comment by djfritz** [comment]
This works for me using dnsmasq 2.75 with both containers and kvm VMs. Can you verify that the host node doesn't already have a route installed for 172.16.0.0/24?

@mkunz7

**Comment by mkunz7** [comment]
All the servers are off right now for the new AC. I'll let you know when it is back up.

The hosts are running Ubuntu 14.04 w/ the latest dnsmasq from the mirror. (apt-get install dnsmasq)

**Comment by jcrussell** [comment]
There's a typo in your dnsmasq command:

`dnsmasq start 172.16.0.1 172.16.0.100 172.168.0.200`

should be

`dnsmasq start 172.16.0.1 172.16.0.100 172.16.0.200`
