### ISSUE TITLE
minitest: leverage `shell`?

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#317]
In the minitest cases, we could call `shell` to check state outside of minimega (e.g. processes, ovs). Thoughts?

@djfritz

**Comment by djfritz** [comment]
Though I can't think of an example, I have this "who tests the tester" sort of question if we're using minimega API to feed results to minitest. 

An alternative would be to add a pragma comment to minitest like golang does for their build pragmas:

    tap create 100 ip...
    #minitest: sh ...

Thoughts?

**Comment by jcrussell** [comment]
I like the idea of pragma comments, will close this issue.
