### ISSUE TITLE
VNC kb record creates a 0 byte file when recording

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#321]
I have three nodes setup

blue10, blue11, blue12

When I login to blue10 and do a:
 vnc kb record blue10 1 /data/mmfiles/1.vnc 

It will create the file as expected.

If I login to blue11 and do a 
 vnc kb record blue11 1 /data/mmfiles/1.vnc

It will create a 0 byte file. The same is true for blue12.

As a workaround I have just been doing VNC records from the first node.

**Comment by jcrussell** [comment]
How do you connect to the VNC session? My guess is that you're tunneling through blue10.

This is an implementation quirk -- minimega can only records kb/fb when it is acting as the tunnel for the VNC session (thus allowing it to snoop messages).

**Comment by mkunz7** [comment]
That would make sense.

I ssh into a jump box with a tunnel to blue10 running web. I do some stuff in novnc and it records fine on blue10, just not on 11 or 12.

I'm not sure how you would fix that. As a workaround you can start web on the other nodes and make another tunnel on the jump box. Definitely a weird quirk people should know about.

**Comment by djfritz** [comment]
We commented on this in a roundabout way internally.

Right now the vnc service allows capture/playback to and from whatever node, so long as the file exists locally. That is inconsistent with the existing minimega semantics of using meshage to tell another node to do something locally. I still think we should ditch the `host` parameter of this API, and just force users to record/playback locally. 

We can fix the 'you must have the file' issue by layering in the `file:` handler, which I should be done with today.

**Comment by djfritz** [comment]
So is this invalid? I got the file transfer shorthand merged yesterday, so we could change the API now and still have a usable solution if we agree that's the way to go.

**Comment by jcrussell** [comment]
Hm, we still have the implementation quirk that you have to tunnel VNC through minimega in order for the recording to work (and that that minimega instance has to have a record entry for the VM). I'm not sure how best to resolve this other than always run minimega in front of the VM's VNC port.

**Comment by djfritz** [comment]
Ahh right. The "distributed" solution I originally recommended would have to be accomplished by trunking VNC traffic over meshage or some other roundabout way. Let's leave the vnc API as it is then.

So, again, is this issue invalid?

**Comment by jcrussell** [comment]
Yes, invalid -- perhaps we should add documentation explaining the intended usage?

**Comment by mkunz7** [comment]
I agree with closing, but can we update the help menu to make a note that VNC won't record VNC from VMs on other nodes in the mesh. You have to start the web interface on the other nodes and use vnc there.
