### ISSUE TITLE
Update mac address in docs

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#322]
When you set mac addresses via minimega, it doesn't warn that the mac address you are trying to use may not be usable by your os driver. 

It just forces it and you will have no idea why it can't get a dhcp lease. I was using 00:00:00:00:00:01, rookie mistake I know and it wouldn't receive a dhcp lease, changing the mac address fixed it. Recently I was at a hotel and I connected via wifi. I wanted to not pay for wifi again so I tried to spoof the address onto my ethernet adapter, and it would refuse to set. Changing the ending number by one would let it set, but not connect. Lesson learned there are certain addresses where the operating system driver just says no.

We don't have to warn users per se, but we should update the docs to use mac addresses that will likely work. 
"vm config net 100,00:00:00:00:00:00 101,00:00:00:00:01:00 102,00:00:00:00:02:00"
Will likely not work depending on your os ethernet driver and dns server.

"vm config net bridge0,100,00:11:22:33:44:55" will likely cause issues too

Windows ethernet drivers tends to be more sensitive to their address. From what I read here Locally administered mac addresses start with x2, x6, xA, xE and multicast addresses of x3,x7,xF. So anything in those ranges are generally safe. http://serverfault.com/questions/40712/what-range-of-mac-addresses-can-i-safely-use-for-my-virtual-machines

**Comment by djfritz** [comment]
We already have the backend of something like this with https://github.com/djfritz/minimega/commit/afce9c493671e5ae7b9143d522389102f77683d9

By default minimega will only generate valid mac addresses using a map of known allocations. We could add a warning if there is a user supplied mac that isn't in this table.
