### ISSUE TITLE
minimega: rewrite capture api to use gopacket

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#331]
see summary. The current implementation is bad.

**Comment by jcrussell** [comment]
I can probably tackle this after finishing namespaces.

**Comment by jcrussell** [comment]
I looked at this a bit today. What's the goal here?

 * Do we want to eliminate the gopcap package? It wouldn't be too difficult to use `gopacket/pcapgo` to create a reader/writer and then copy packets in a goroutine.
 * Do we want to clean up the decoding of Packet/Header/Record? There isn't a layer for Netflow so we would essentially just move our code into the gopacket layer format.

I did clean up ipmac using gopacket (see cee29d20e2de8be17d9092207ea0d0cdd9402b12).

**Comment by jcrussell** [comment]
I don't think there's an immediate need for this in 2.3. `ipmac` is now gopacket based once #683 is merged.
