### ISSUE TITLE
minimega: vnc port collisions 

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#342]
When launching VMs, if a network tap already exists that we want to allocate for a VM, we increment the tap name (mega_tapX) and try again until we find a tap name that isn't in use. 

We have a similar issue with the VNC port we ask qemu to use. By default we tell qemu to use 5900+<vm id>. If a port happens to be in use (not uncommon for VNC), then we just mark the VM in the error state and give up. We should instead do something similar to the tap solution.

The best solution would be to check if the port is in use first (/proc/net/tcp and friends show this) and decouple the port<->id map. Another solution would be to have qemu pick the port and then ask qemu what port it used (via qmp, a quick look doesn't look like qemu has a qmp interface for this yet). 

@jcrussell @floren @bjwrigh

**Comment by jcrussell** [comment]
Sounds easy enough. I assume that we'd add another field to `vm info` so that users and the web interface can figure out what port to talk to for a given VM?

**Comment by djfritz** [comment]
I suppose. Also the web interface needs a patch to lookup the correct port.
