### ISSUE TITLE
container based router

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#344]
We need a fully opensource container router image that takes one or more configs for deployment. If we get something solid, we'll tease out an API for it and replace the 'vyatta' API with this.

I'd like:

- routing (ospf, ospf3, bgp, static)
- dhcp with static ip options
- optional static ips for all interfaces 
- dns
- full ipv6 support everywhere
- RAD/slaac support for v6
- firewall (just iptables is fine)
- snmp would be neat to have
- centralized logging
- some agent for making changes perhaps instead of a direct configs for all of the tools

@floren @bjwrigh thoughts?

**Comment by floren** [comment]
Quagga could take care of our routing needs, I think.

DHCP and DNS may be best suited by dnsmasq. As per my recent patch, dnsmasq can monitor directories via inotify so it'll automatically pick up any changes you make to host records, static IPs, or DHCP options. Not sure what it's capable of in terms of all the different DNS records (A, CNAME, MX, etc)

How crazy we want to get with centralized configuration is a big question. Given how much string processing is involved I'd say we might want to use more of a scripting language to write configuration tools (versus Go. Consider sed+awk, maybe python, or even Perl).

**Comment by rstrong** [comment]
More food for thought would be to look at bird for routing.

**Comment by djfritz** [comment]
Our interim image we testing with is already using bird.

**Comment by djfritz** [comment]
This should also include a simple firewall
