### ISSUE TITLE
Enhance vnc replay

### ISSUE THREAD

**Issue by floren** [sandia-minimega/minimega#345]
We should extend the vnc playback parser so that in addition to keyboard and mouse events, we can have "load file" events in a VNC file. This will allow us to create a file containing a series of separate VNC playback files which will be played in sequence on a given VM, e.g.:

    0 LoadFileEvent,login.vnc
    1112233 LoadFileEvent,openbrowser.vnc
    1144000 LoadFileEvent,browseslashdot.vnc

**Comment by djfritz** [comment]
@jcrussell this is a slick idea.

**Comment by jcrussell** [comment]
Nice idea! Should be pretty simple to implement. Are you implementing it recursively? Hopefully people don't create `busy beaver` scripts:

```
$ cat busybeaver.vnc
0 PointerEvent,mask,x0,y0
100 PointerEvent,mask,x1,y2
100 LoadFileEvent,busybeaver.vnc
```

Perhaps we should have an `ExecFileEvent` which behaves like `exec` -- replacing the currently executing vnc playback with a new input file.

**Comment by jcrussell** [comment]
@djfritz -- think we need `ExecFile` or should we just assume people won't want this behavior?
