### ISSUE TITLE
minimega: vnc api still cannot match on vm name

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#359]
see summary, we're forced to use the vm id still. I thought we fixed this already, so maybe I'm just being dumb somewhere.

@jcrussell @floren

**Comment by djfritz** [comment]
more detail: this was a remote host and vm name that didn't match. I don't know if the problem exists locally as well or not.

**Comment by jcrussell** [comment]
Just tried:

```
vm launch kvm 1
vm start all
vnc kb record localhost vm-0 foo
```

And it looks like it worked. Think we can close this.

**Comment by djfritz** [comment]
Can you try it with a remote node. I had this with:

vnc kb record remotenode foo

And it failed.

**Comment by djfritz** [comment]
minimega$ mesh send ccc2 .columns name,state vm info
    host | name | state
    ccc2 | foo  | RUNNING
    minimega$ vnc kb record ccc2 foo foo.kb
    Error (ccc1): vm not found: foo
    minimega$ vnc kb record ccc2 0 foo.kb
    minimega$ vnc
    host | host | name | id | type      | filename
    ccc1 | ccc2 | foo  | 0  | record kb | foo.kb
    minimega$ 

@jcrussell
