### ISSUE TITLE
minimega: fallback when gob fails

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#404]
If we try to gob encode something in meshage and it's not encodable, things will hang.

For example, in a recent bug, the vms weren't gob encodable so running `mesh send all vm info` would hang. We should somehow push the error through and close the channel that is causing it to hang.

**Comment by djfritz** [comment]
We control the entire ecosystem - there should never be a time when we attempt to encode something that cannot be encoded or isn't already registered. This should reasonably only pop up when we're developing/testing new things right?

If this is a very simple fix then we should go for it, but if there's a refactor involved I say the burden is on the developer and we move on.

**Comment by jcrussell** [comment]
Yeah, should only occur during development. I agree that we should only fix it if it's easy.
