### ISSUE TITLE
create buildbot/minitest scripts

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#442]
see summary. Create scripts to build and generate simple html output suitable for a cronjob based buildbot.

**Comment by jcrussell** [comment]
We should also reject code that don't conform to `go fmt`.

**Comment by jcrussell** [comment]
https://travis-ci.org/ can run both `go fmt` and `go test` and has nice integration with github.

We'll have to do something separate for minitest.

**Comment by jcrussell** [comment]
Can also throw `minifuzzer` into this.

**Comment by djfritz** [comment]
https://treeherder.mozilla.org/#/jobs?repo=mozilla-inbound

**Comment by jasoncontrib** [comment]
@djfritz @floren Thoughts on where we want to store kernel/initrd pairs and tars of container FS's? Build process needs to pull them down for tests to run.

E.g. Do we want to upload more files a la https://storage.googleapis.com/minimega-files/minimega-2.3-minirouter.tar.bz2? Or diversify and use Git Large File Storage in the same repo / separate repo?

https://git-lfs.github.com/

**Comment by floren** [comment]
I'd probably rather not put it in Google storage because that costs me
money.
