### ISSUE TITLE
web: make namespace-aware

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#474]
Should be able to have a dropdown in the page that allows you to select a namespace. Should then only see the hosts and VMs that belong to that namespace.

**Comment by glattercj** [comment]
Should this behavior include ACLs/web login to facilitate multi-tenancy? E.g. when a user logs in, they only have access to their namespaces.

**Comment by djfritz** [comment]
No

**Comment by jcrussell** [comment]
Rolling into #686.
