### ISSUE TITLE
minimega: OOM killed

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#478]
Hammered on minimega for about 10 hours and it was OOM killed. I suspect that it may be the command history (`minicli.history`) which grows indefinitely that caused it to run OOM. We should probably limit the history and then see if we can reproduce this.

**Comment by djfritz** [comment]
HA!

**Comment by jcrussell** [comment]
Thinking about an upgrade to the `debug` API:

```
            "debug",               // outputs the stats from runtime
            "debug memory <file>", // dump memory profile to file
```

This would make it easy to dump the memory profile every hour until it crashes. Thoughts?

**Comment by djfritz** [comment]
Sounds good to me. We could add a CPU profile too while we're at it.

**Comment by jcrussell** [comment]
CPU profiles are stopped/started -- we could have the length of the snapshot as a parameter to simplify the API (no stop/start commands).

```
            "debug <cpu,> <duration> <file>", // dump CPU profile for duration seconds to file
```

**Comment by djfritz** [comment]
Up to you, we can defer adding CPU profiles if need be. Or we can enable it from the debug API and have the stop occur in the teardown() signal handler

**Comment by djfritz** [comment]
Is this fixed now? @jcrussell

**Comment by djfritz** [comment]
Oh wait, no. I wasn't paying attention.

**Comment by jcrussell** [comment]
Merging #481 and #484 will close this.

**Comment by jcrussell** [comment]
Both tickets merged... Closing ticket.
