### ISSUE TITLE
ron/miniccc: add negation to `cc filter`

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#488]
Before namespaces, we could launch all the clients on a single host and run `cc background` without any filters to make them all start `protonuke`. Now, targeting these VMs is more complicated because the clients could be split between multiple hosts. We can currently specify a CIDR for ip (e.g. 100.0.1.0/24). It would be nice to also be able to specify ips to excluded, such as the router on 100.0.1.1. The syntax would be something like `ip=100.0.1.0/24 ip!=100.0.1.1`.

**Comment by jcrussell** [comment]
Alternatively, we could add `cc filter tag=...` and tag the VMs appropriately when we launch them.

**Comment by djfritz** [comment]
Yes to both of these ideas!

**Comment by djfritz** [comment]
It might be cool to instrument a first-come limited call as well:

    cc filter limit=100
    cc background ...

So only 100 commands get farmed out (random based on who got to it first). It would require a bigger change to the protocol, but we've needed something like this before. It could just as well be instrumented by minimega and the tag= filter.

**Comment by jcrussell** [comment]
Hmm, I'm liking the `tag=` filter idea a lot... perhaps too much. Why do we even need the other filters? We probably should keep them since they might still be useful but I can definitely see them being superseded by `tag=` filters.

We can use random to tag our protonuke clients differently to create more heterogeneous subnets. Something like:

```
r=$((RANDOM%10))
if (( r < 4 )); then
    echo vm config tag http-client=true
elif (( r < 6 )); then
    echo vm config tag smtp-client=true
else
    echo vm config tag ftp-client=true
fi

echo cc filter tag=http-client=true
echo cc background /protonuke -http
...
```
