### ISSUE TITLE
minimega: interruptible commands

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#506]
It's way too complicated to support interrupting any commands at any point but some long-running commands (e.g. `mesh send` and `read`) could be interrupted with Ctrl-C. Each of the long-running commands have a loop -- we would just check whether to abort after each iteration. We would need to override the signal handler for the duration of the command and, probably, change it so that the user has to Ctrl-C twice to actually quit.

**Comment by jcrussell** [comment]
This could also apply to the scheduler.

**Comment by djfritz** [comment]
What's the use case for ever needing this? The scheduler should have an appropriate timeout or other heuristic for escaping starvation.

**Comment by jcrussell** [comment]
My thoughts:

`mesh send` -- we no longer have timeouts so if a remote host dies, it blocks forever.
`read`/scheduler -- user realized a mistake and wants to abort rather than run to completion.

**Comment by djfritz** [comment]
I don't know what the best approach is for read/scheduling, but meshage can detect when a connection drops from the lack of heartbeats. When that happens it should send an error up using the TID of any in-flight messages intended for that host. That allows for a graceful error report upstream and over whatever command interface the user is on.

**Comment by jcrussell** [comment]
This is probably not worth implementing for now.
