### ISSUE TITLE
Minicli test fails on build

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#516]
```
TESTING
?   	apigen	[no test files]
?   	gonetflow	[no test files]
ok  	gopacket	0.003s
?   	gopcap	[no test files]
ok  	gopnm	0.034s
?   	goreadline	[no test files]
?   	igor	[no test files]
?   	iomeshage	[no test files]
?   	ipmac	[no test files]
?   	meshage	[no test files]
?   	miniccc	[no test files]
# minicli_test
src/minicli/minicli_test.go:103: cannot use func literal (type func(*minicli.Command, chan minicli.Responses)) as type minicli.CLIFunc in field value
FAIL	minicli [build failed]
```

Is my goread out of date or something? I couldn't figure it out can someone point me in the right direction?

ubuntu 14.04
apt-get install libpcap-dev libreadline-dev git qemu qemu-kvm openvswitch-switch dnsmasq unzip python-jinja2
using go 1.6 https://www.digitalocean.com/community/tutorials/how-to-install-go-1-6-on-ubuntu-14-04

**Comment by mkunz7** [comment]
https://github.com/sandia-minimega/minimega/commit/11cede1ff89d4071ffa93a689361e7e55df5552f

**Comment by jcrussell** [comment]
The function type for CLIFunc changed in PR #500 but I forgot to update the tests. It's an simple fix that I'll do tomorrow morning.
