### ISSUE TITLE
Namespace vlan range reservations

### ISSUE THREAD

**Issue by derhart** [sandia-minimega/minimega#527]
From my experience running multiple namespaces, it looks as though the "vlans range" call will reserve a block of vlan ids for the namespace, even if the namespace only uses a subset of that range. When you attempt to deploy using another namespace, issues arise because of the potentially, overly aggressive reservation of vlans.

Who should manage the vlan state? Will minimega and its scheduler be managing vlan ranges for namespaces? In our deployment scripts, we reference vlans by an alias (MGMT, EXP_1, EXP_2, etc.), not a vlan id number. Using an alias makes configuration very easy and looks to be the preferred method with the namespace addition. We aren't aware of what numbers will be assigned to the vlans until the namespace is deployed. We can track how many vlans we need to deploy the namespace, but that would mean storing more state on our side; namely vlan ranges, and start/stop ids for each namespace. It would also mean changing from an alias to a number.

It's not a huge deal to switch around our code, but I wanted to know more about how you envision this working before we opted for a design direction.

**Comment by jcrussell** [comment]
If there's a range of VLANs you have to use for all namespaces, set the "global" vlans range *before* entering a namespace. If you to specify a range of VLANs for a particular namespace, that returns an error if the ranges overlap. For example:

```
minimega$ vlans range
namespace | min | max  | next
          | 101 | 4096 | 101
minimega$ vlans range 300 400
minimega$ vlans range
namespace | min | max | next
          | 300 | 400 | 300
minimega$ namespace foo
minimega[foo]$ vm config net dmz
minimega[foo]$ vm config net
[mega_bridge,dmz (300)]
minimega[foo]$ namespace bar
minimega[bar]$ vm config net dmz
minimega[bar]$ vm config net
[mega_bridge,dmz (301)]
```

minimega will return an error if there aren't any VLANs left in the specified range.

Does this help? Let me know if you want to schedule a call to chat more about this.

**Comment by derhart** [comment]
Yes, that makes sense. Our code is assigning a range per experiment, which is where the problem is coming in. It sounds like you are managing the vlan state much like I expected, which is great.

As an aside, how do I move from a namespace back to the "global" namespace?

**Comment by jcrussell** [comment]
Great.

`clear namespace`.

**Comment by derhart** [comment]
I found that just after I commented, but thanks for the help. I'll close this because I think I know what we need to do from our side.
