### ISSUE TITLE
minimega: add `vms` column to `host`?

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#539]
Should we add a count of the number of vms to `host`? I launched a bunch of VMs with namespaces and it's non-trivial to figure out how many landed on each host. I know we /can/ get the info elsewhere but this seems useful to me.

Alternatively, we could add a `.count` API...

**Comment by djfritz** [comment]
`.count` is a slippery slope - eventually we'll want all of binutils on the minimega command line as opposed to just using `wc` and pipes. Adding a vm count to `host` sounds good to me.

**Comment by jcrussell** [comment]
Adding `vms` and `vmsall` -- `vms` for current namespace, `vmsall` for all namespaces.
