### ISSUE TITLE
Pcap capture 0 bytes

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#545]
minimega  2016-05-08 works
minimega  2016-05-26 fails

Did a fresh install of latest same issue, something has changed.....

**Comment by jcrussell** [comment]
Might be an issue with the refactored bridge code.

Unless you're using the `namespace` API, I would avoid master for a few more weeks. This branch fixes the capture crash (but is otherwise 2.2):

https://github.com/jcrussell/minimega/tree/2.2.1

**Comment by djfritz** [comment]
We never did resolve how to patch stable...
