### ISSUE TITLE
minimega: `vm save` location

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#552]
Currently, we save VMs in `$minimega/saved_vms/...`. It seems preferable to save the VMs in `$minimega/files/saved_vms/...` so that they can be relaunched via the `read files:saved_vms/...`.

**Comment by djfritz** [comment]
Does this api even get used? Should we just ditch it?

**Comment by jcrussell** [comment]
No clue, I've just been maintaining it because it's there.

Perhaps we need to have the option to send up minimega usage statistics...

**Comment by jcrussell** [comment]
@djfritz -- kill the API?

**Comment by djfritz** [comment]
merging into #557
