### ISSUE TITLE
minimega: `cliPreprocessor` not expanding files

### ISSUE THREAD

**Issue by glattercj** [sandia-minimega/minimega#555]
In the latest master version (5672369636d87a5ef2ac6e822738903661d44ab7), when starting an experiment from a headnode with several mesh peers (deployed with `deploy launch ...`), the snapshot files (in /tmp/minimega/files) aren't getting copied to the mesh peers. This causes all the vms to have the `ERROR` state when the experiment is started.

I rolled back to f84f6aeb8648512bc044c0528288e41844228b10 (2016-04-26) and things still work there.

**Comment by jcrussell** [comment]
Can you email me part of your launch script that reproduces it? I haven't noticed the issue with my scripts. #524 touched this code in early May.

**Comment by glattercj** [comment]
Emailed.

**Comment by jcrussell** [comment]
Found the problem:

```
func cliPreprocessor(c *minicli.Command) error {
    if c.Source != GetNamespaceName() {
        return nil 
    }   
```

We didn't bother setting the namespace when invoking `vm config disk` so the Source and active namespace don't match. Fix is to prepend namespace command on all commands from `Namespace.Launch`.

**Comment by jcrussell** [comment]
@glattercj -- I fixed the above problem but that's only half your problem. When I created the snapshot as you did and then tried to launch a VM from it, I saw the following error:

```Could not open backing file: Could not open '/root/linux.qcow2'```

We don't have a way to automatically fetch the backing file (compounded if it's not even in the minimega files directory). @djfritz -- thoughts?

**Comment by djfritz** [comment]
namespaces are supposed to copy files on demand - this is why we have the file get behavior of returning immediately without error if the file exists locally - the namespace behavior should be to always 'file get' a file before attempting to use it (if the user is pointing to a file in the files directory or using the file: prefix.

**Comment by jcrussell** [comment]
I agree but I think you missed the point -- currently, the backing image for the snapshot must be explicitly copied because it is never referenced via a `file:` prefix.

I thought of a hack that might fix this -- `vm config tag backing-image file:<image>`. This will get sent to the node where the VM is scheduled and will cause a file get. Suuuuper hacky but it should work. Unless we want to start reading qcow images to find dependencies, I'm not sure there's a clean solution.

**Comment by djfritz** [comment]
`qemu-img info <filename>` will list the backing files associated with a snapshot. We could extend the disk API include something like `disk info` or something that lists the backing-files among other things. Namespaces could then leverage that to ensure all requisite files get copied around. Thoughts @jcrussell ?

**Comment by jcrussell** [comment]
Sounds good. Probably should split this ticket into a bug in the cliPreproccessor and a new feature request for `disk info`/copying backing files.
