### ISSUE TITLE
Binary netflow missing a byte

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#558]
The first byte of the netflow header is being omitted in every packet after the first packet.

```
capture netflow bridge experiment socket udp <ip>:<port> raw
```

**Comment by jcrussell** [comment]
Possibly there's an off-by-one error here: https://github.com/sandia-minimega/minimega/blob/master/src/gonetflow/gonetflow.go#L296

`net.Conn.ReadFromUDP` returns the number of bytes written to the buffer. `b[:n]` would be the entirety of the written buffer. Seems odd that we would omit the last byte.

@mkunz7 -- want to try removing the `-1` to see if that works?

**Comment by mkunz7** [comment]
Alright took a while to get everything coordinated, that fixed the issue. :)
