### ISSUE TITLE
minimega: read should stop after error

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#560]
Doesn't look like read stops after a command returns an error:

```
minimega$ shell cat test
foo: echo before
shell asdfasdfas
echo after
minimega$ read test
foo: before
Error (foo): exec: "asdfasdfas": executable file not found in $PATH
foo: after
```

**Comment by djfritz** [comment]
See the PR that goes with this - I don't see this as an error - there are plenty of cases where you get false errors and want to continue. In fact, it's the norm for most experiments we run.

**Comment by jcrussell** [comment]
Hmm, break on error was the original behavior in 1.0:

```
 263                 for {
 264                     l, _, err := r.ReadLine()
...
 279                     if resp.Error != "" {
 280                         break // stop on errors
 281                     }
 282                 }
```

I (incorrectly) tried to replicate that behavior in the 2.0 refactor and we've lived with a non-break-on-error read ever since. Break on error is the behavior described in the help for read -- we should update the help to note that read does not stop on the first error.

**Comment by djfritz** [comment]
So then it was a happy side effect that we changed the behavior in 2.0 - I would have ended up asking for this behavior should the 'stop on error' behavior still been in place.

**Comment by jcrussell** [comment]
Okay -- I'll update the documentation to state the read doesn't stop on commands that return errors. If it reads an invalid command, should it stop then?

**Comment by djfritz** [comment]
Ah yes, good idea. We *should* stop on invalid commands.
