### ISSUE TITLE
Add support to save current VM state to new snapshot file.

### ISSUE THREAD

**Issue by glattercj** [sandia-minimega/minimega#581]
Use case:
Fire up vm in non-snapshot mode, make some changes, realize you want to save the changes but not write back to backing image (i.e. create a new snapshot from current snapshot+changes).

From @djfritz: This can be accomplished outside MM using something like the following: 

``` bash
vm qmp <vm id> '{ "execute": "blockdev-snapshot-sync", "arguments": { "device": "ide-hd0", "snapshot-file": "/tmp/foo.qcow2", "format": "qcow2" } }'
```

**Comment by jcrussell** [comment]
Something like:

```
vm snapshot <vm name> <disk ID> <file>
```

where `<disk ID>` is the index into `vm config disk`? Seems like a small lift.

**Comment by jcrussell** [comment]
Is this even possible? The disk has already been written to since it was in non-snapshot mode.

If it is possible, it's an "advanced" use that should use the `vm qmp` API.
