### ISSUE TITLE
Start a developer doc

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#604]
At least to start, we have a ton of helper functions in the source (writeOrDie(), vm.path(), ...) that get added without fanfare and embedded in other PRs that other devs don't usually know about *cough* @jcrussell *cough*. We need a doc that itemizes all of these with notes. 

@jcrussell

**Comment by jcrussell** [comment]
I don't think it's worth writing a developer doc for this. It will be out of date by the time it's written and mostly a waste of time (developers probably haven't read the last developer article I wrote about namespaces).

The functions should all be commented and any that aren't need to be. We should generate godocs for all the packages (including the `main` packages) and put them up on minimega.org instead.

**Comment by djfritz** [comment]
nobody wants to do this
