### ISSUE TITLE
minimega: contexts are not minding their own business

### ISSUE THREAD

**Issue by glattercj** [sandia-minimega/minimega#608]
@jcrussell

**Comment by jcrussell** [comment]
I wasn't able to replicate this with two hosts running the following commands:

```
sudo bin/minimega -level info -degree 2 -context foo

sudo bin/minimega -level info -degree 2 -context bar
```

**Comment by glattercj** [comment]
When I saw this issue, we were using a version from April that still had the snapshots working (before ticket-555 was merged). This seems to have been fixed sometime between then and now, so I'm going to close this.
