### ISSUE TITLE
minimega: rewrite namespaces to use meshage

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#621]
Create new type:

```
type meshageLaunch struct {
    VMConfig
    VMType
    Names     []string
    Namespace string
    TID       int32
}
```

and send that over meshage to the node that should launch the VMs. Should actually make things a lot simpler and less error-prone, why didn't I think of it sooner.

**Comment by djfritz** [comment]
@jcrussell Is this done now?

**Comment by jcrussell** [comment]
Yup!
