### ISSUE TITLE
protonuke: add IRC client

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#622]
Hey guys, let's hear some chatter out there.

**Comment by mkunz7** [comment]
I wrote something for fritz, it's not in go though. You can use it with cc.

**Comment by jcrussell** [comment]
We'll probably want something in Go eventually so that it integrates with protonuke. Good to know it's floating around though.

**Comment by jcrussell** [comment]
Maybe we can add some CC stuff to this.
