### ISSUE TITLE
minimega: `cc proccess` improvements

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#644]
It would be better if `cc process list` were based on`cc filter` rather than the `<vm id, name, uuid or all>` argument.

`cc process kill <pid or all>` is a bit inconvenient since you have to look up the PID first before killing something. Perhaps instead, we should store a counter in ron/client.go and kill based on the counter value rather than the actual PID. Alternative, we could also support something like `pkill` or `killall`.

**Comment by jcrussell** [comment]
Rolling this into #666.

**Comment by djfritz** [comment]
captured in #666
