### ISSUE TITLE
VNC - Multiple NoVnc Users

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#671]
When two people try and use novnc to share a VM it only works the first time.

Scenario:
User 1 and User 2 open a browser and open novnc on the same vm. 
User 2 closes the browser and then tries to reconnect and novnc errors with:
Server disconnected (code: 1000)

![screen shot 2016-09-26 at 4 43 01 pm](https://cloud.githubusercontent.com/assets/5001991/18852934/5d7a59e6-8408-11e6-80e0-e32e82038276.png)

**Comment by mkunz7** [comment]
25min later the issue resolves itself, temperamental bug

**Comment by x64x6a** [comment]
I can't recreate the issue, but I have a hunch it may have been an issue with qemu's implementation of vnc

**Comment by jcrussell** [comment]
Do you know what version of qemu?

This looks relevant: https://github.com/kanaka/noVNC/issues/183

**Comment by mkunz7** [comment]
qemu-x86_64 version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.4)

**Comment by jcrussell** [comment]
I just opened many tabs for the same VM and closed/reopened a few without seeing this issue.

QEMU emulator version 2.6.0 (qemu-2.6.0-5.fc24)

Please reopen this issue if it recurs.
