### ISSUE TITLE
minimega: deprecate targeting VMs by ID

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#680]
Namespaces makes targeting VMs by ID ambiguous so we should eliminate the ability to target VMs by ID.

**Comment by mkunz7** [comment]
Maybe I don't understand things fully, but why do we need to remove this? It seems to me like we could have it as desired functionality?

Pretend you have servers:
```
server1: vm id 0: name:linux namespace: a
server2: vm id 0: name:linux2 namespace: a
```

The issue comes with running
```
vm kill 0
```

So the issue is it won't know which vm to kill. Why can't we just assume you are referencing the local machine from where you issued the mini command from? Or even just issue the kill command to both?

**Comment by jcrussell** [comment]
The two main drivers here are that targeting VMs by ID is:

 * unrepeatable -- you can't run the same script multiple times and get the same results (unless you restart minimega each time and are the sole user)
 * ambiguous -- VM IDs are unique by host, not by namespace

Encouraging users to move towards VM names, which are both repeatable and unambiguous, seems best. If we did add special logic everywhere that takes a VM, that would complicate the code and make it more difficult to explain to users.

Why wouldn't you want to kill VMs by name? Presumably, you're using the name or disk image to find the right VM ID in `vm info` -- if you give VMs reasonable names, this should simplify your workflow.

**Comment by mkunz7** [comment]
Some of the scripting libraries we use generate super long names and it's far easier to use vm id # than it is to copy and paste the name. I'm all for reducing program complexity, but I'm hesitant to the this change.

Perhaps this begs a need for a shortened unique vm identifier that is namespace aware.

**Comment by jcrussell** [comment]
VM names have tabbed completion, does that help?

**Comment by mkunz7** [comment]
That's fixed?

**Comment by jcrussell** [comment]
Not from -attach, yet. We should have tabbed completion working from -attach before we remove target VMs by ID.
