### ISSUE TITLE
minimega: wrong VLAN alias in 'vm info'

### ISSUE THREAD

**Issue by glattercj** [sandia-minimega/minimega#724]
When running multiple experiments in multiple namespaces, executing the command: `.column name,vlan namespace foo vm info` returns the correct VLAN ID, but the wrong VLAN alias. E.g. the vm name will be something like `foo-vm1`, and the VLAN will be `[barbaz//EXP1 (105)]`. The ID is correct, but the alias is wrong.

**Comment by jcrussell** [comment]
If you `clear namespace` and then run `.filter vlan=105 vlans` do you see more than one entry?

**Comment by glattercj** [comment]
No, the output for `vlans` is correct. I've only seen the bug in `vm info`.

**Comment by jcrussell** [comment]
Can you send me a script where this happens?

**Comment by jcrussell** [comment]
I know why this is broken now... `printVLAN` in `BaseVM.info` should use the VM's namespace rather than the active namespace. This bug should only appear when you run `vm info` from outside a namespace.

**Comment by jcrussell** [comment]
This bug is weird... how does the same VLAN ID have multiple aliases?

**Comment by jcrussell** [comment]
Please reopen if you can reproduce.
