### ISSUE TITLE
minimega: minicli Header uniformity

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#731]
It would be nice if all the Headers were lowercase and a single word. This annoys me:

`.columns Bridge,"Trunk ports"  bridge`

**Comment by jcrussell** [comment]
We should also move units to the column headers rather than have the units in every row.

**Comment by jasoncontrib** [comment]
Is there a way to add units to the column headers without having to type them when using the .columns filter syntax?

**Comment by jcrussell** [comment]
We support prefixes elsewhere -- we could do with `.columns` as well.

**Comment by djfritz** [comment]
Are you talking about the apropos support we have in minicli?

**Comment by jcrussell** [comment]
Yup. What do you think?

**Comment by djfritz** [comment]
Sounds perfect to me - the uninformed user would probably expect to be able to shorthand column names just the same as the cli terminals anyway.

**Comment by jasoncontrib** [comment]
Do we want to support apropos matches / prefixes with .filter, too?

**Comment by jcrussell** [comment]
Yup.

**Comment by jcrussell** [comment]
Closed by #800
