### ISSUE TITLE
minimega: parsing dnsmasq version

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#737]
Seeing this error on debian:

```
WARN main.go:201: cannot parse dnsmasq version: `nettle_hashes'
```

Problem is an unexpected line in the output:

```
$ dnsmasq -version
dnsmasq: Symbol `nettle_hashes' has different size in shared object, consider re-linking
Dnsmasq version 2.76  Copyright (c) 2000-2016 Simon Kelley
Compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
```

We could change the parser to scan until it sees the right line. Seems like an upstream issue though.

**Comment by x64x6a** [comment]
I usually installed dnsmasq 2.75 from [source](http://www.thekelleys.org.uk/dnsmasq/dnsmasq-2.75.tar.xz) and I never seemed to have any issues

**Comment by djfritz** [comment]
I'll get to this today.

**Comment by jcrussell** [comment]
Yeah, this issue is from using the prebuilt debian packages in testing. Doesn't happen on my machine.

**Comment by djfritz** [comment]
So should we ignore this until it gets resolved in upstream?

**Comment by jcrussell** [comment]
I'm fine with ignoring it.
