### ISSUE TITLE
minimega: Add comparison expression support to minitest

### ISSUE THREAD

**Issue by csymonds** [sandia-minimega/minimega#753]
Support value comparisons for "==", "<", ">", "<=", ">=", "!=", and "|" in test expressions.

It would be highly beneficial to add in support for comparison expressions to minitests that would allow verifying whether captured values fall within a range. Currently we can only test exact log output, and this would allow more flexibility in how we test. This should include support for piping, again to add some flexibility for testing expected vs. actual output.

**Comment by jcrussell** [comment]
I was thinking about this a bit for testing the QoS API. We planned on using the bandwidth to test whether it was in the correct range. The bandwidth column isn't a simple integer though... it's something like "x/y (rx/tx MB/s)". It would be nice to be able to extract values using regular expressions and then do the comparison.

Aside: we should probably move units to the header.

I think we can allow the most flexibility by running things through external tools. `|` seems like a good choice. For example, to test that the RX MB/s is between 90 and 100, we could use:

```
.columns bandwidth vm info | awk -F'/' '{ if ( 90 <= $1 && $1 <= 100) { print "OK"; } }'
```

@djfritz

**Comment by jcrussell** [comment]
We've talked about this a more offline and I'm not sure if this is worth pursuing at this time.
