### ISSUE TITLE
minimega: vnc bug

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#759]
It doesn't look like the last command in a recording is being executed.

**Comment by jasoncontrib** [comment]
Not able to reproduce; any tips for surfacing this bug? Not seeing the bug-indicating-key-repeat-behavior with the following test setup:

test.mm
```
web
vm config kernel /data/minimega/images/miniccc_virtio.kernel
vm config initrd /data/minimega/images/miniccc_virtio.initrd
vm config net A
vm launch kvm host1
vm start host1
vnc play host1 /test.vnc
```

test.vnc
```
503553298:KeyEvent,true,h
54053754:KeyEvent,false,h
```

**Comment by jcrussell** [comment]
I wasn't able to reproduce this either.. odd. Can you try with a VM that has a GUI? Check /scratch for debian_irc.qcow2 on the CCC nodes.

**Comment by jasoncontrib** [comment]
I was able to reproduce it with a terminal window opened inside the GUI of a VM on debian_irc.qcow2, interesting.
