### ISSUE TITLE
bird6 doesn't work properly when static routes are defined

### ISSUE THREAD

**Issue by floren** [sandia-minimega/minimega#761]
If you've defined IPv4 static routes with minirouter (and possibly in other cases, but static routes are definitely one case), bird6 will fail to start because bird and bird6 currently share a config file (/etc/bird.conf) and the IPv4 static routes throw bird6 through a loop. I believe bird (v4) will also fail to start if you've defined static ipv6 routes.

The solution is to generate the same file twice but put only v4 routes into one and v6 routes into another.

Error message:

    bird6: /etc/bird.conf, line 24: syntax error

The line 24 in question:

    route 10.0.0.0/24 via 192.168.0.1;

**Comment by jcrussell** [comment]
@floren: this was fixed by #764, right?

**Comment by floren** [comment]
Yep
