### ISSUE TITLE
meshage race / deadlock

### ISSUE THREAD

**Issue by floren** [sandia-minimega/minimega#762]
After doing a 'deploy launch', if I run 'mesh status' over and over while I wait for all the nodes to show up, sometimes the minimega process will lock up. I have not yet generated a stack trace, but I expect that there's some lock mismanagement going on. I think if you run 'mesh status' at the same time a new node is negotiating a connection to the mesh, you'll cause a deadlock.

**Comment by jcrussell** [comment]
Looking at the stack trace, here's the hanging goroutine:

```
goroutine 1012 [select, 3 minutes]:
main.meshageSend.func1(...)
        /minimega/src/minimega/meshage.go:196 +0xa3b
created by main.meshageSend
        /minimega/src/minimega/meshage.go:224 +0x29e
```

The head node isn't getting a response from a peer. Still need to keep looking into this. Maybe the peer is listed as a valid recipient before it's ready to accept commands?

**Comment by jcrussell** [comment]
This is going to take a bit of time to figure out a fix for and shouldn't affect users unless they spam `mesh status` while the mesh is forming. Will address in 2.4.

**Comment by jcrussell** [comment]
Not going to figure this out for 2.4.

**Comment by djfritz** [comment]
This is pretty old and doesn't appear to be affecting anyone. Is this still an issue? Just close it until it bothers someone again?

@jcrussell

**Comment by jcrussell** [comment]
Yeah, @floren is just impatient.
