### ISSUE TITLE
minimega: remove `defaultExternalProcesses`

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#787]
What is the purpose of this map? It provides aliases for commands but cannot be updated. We do use it to check for all runtime dependencies which is useful. I suggest we remove it to remove the indirection.

**Comment by jcrussell** [comment]
While we're at it -- we don't need "rm" (os.RemoveAll), "cp" (filepath.Walk/io.Copy), "kill" (syscall.Kill), or "hostname" (os.Hostname).

@jasoncontrib @djfritz

**Comment by jasoncontrib** [comment]
Taking dependency-squashing further -- we could remove the compile-time dependency on libreadline and vendorize:

https://godoc.org/github.com/peterh/liner
https://github.com/chzyer/readline

**Comment by djfritz** [comment]
We do some funky stuff with signal traps and tab completion. We'd need to seriously vet other bindings first.
