### ISSUE TITLE
Feature request:  Expose guest shell from cc command

### ISSUE THREAD

**Issue by bjwrigh** [sandia-minimega/minimega#796]
@jcrussell @djfritz 
Either stay in-context

_minimega:/tmp/minimega/minimega$ cc shell vm1
minimega:/tmp/minimega/minimega$ vm1$ hostname
vm1
minimega:/tmp/minimega/minimega$ vm1$_ 

-or -  Drop back to the previous context(minimega)

_minimega:/tmp/minimega/minimega$ cc {odd named keyword} vm1 hostname
vm1
minimega:/tmp/minimega/minimega$_

**Comment by djfritz** [comment]
What is this asking for? A shell to a miniccc-based guest?

**Comment by jcrussell** [comment]
Yeah -- minicccsh? Or ccsh?

**Comment by djfritz** [comment]
minish

**Comment by jcrussell** [comment]
Not on the roadmap for now.
