### ISSUE TITLE
minimega: create `cc tail`

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#799]
Create an API:

```
cc tail <path/on/guest> <name>
```

miniccc/minimega would start tailing the file in the guest and writing it up to the host.

**Comment by jasoncontrib** [comment]
Adding a couple more questions:

Would the destination path be something like `host:/tmp/minimega/<vm id>/tail/path/on/guest`?

This package can deal with log rotation (detecting file truncation / moves), is that within scope? Doesn't yet support Windows, though.
https://github.com/hpcloud/tail

**Comment by djfritz** [comment]
Let's pass on log rotation, etc. for now - that's out of scope for our use case anyway.

The destination path, when considering our other file creation/storage semantics, should probably be something like `<iobase>/<vm name>_<source filename>` unless otherwise specified (though still rooted in `iobase`). So the api would change to:

    cc mirror/tail/clone/... <path/on/guest> [local filename]

**Comment by djfritz** [comment]
Using the above, we could easily setup a splunk (or elk) forwarder within `iobase`. Something like:

    <setup a forwarder in /tmp/minimega/files/foo>
    # specifying a directory keeps the autogenerated filename
    cc filter ...
    cc tail/whatever foo.log foo/

Then you end up with a forwarded directory full of foo.log prepended with the vm name. Thoughts?

**Comment by jcrussell** [comment]
We'll be a little inconsistent with existing `cc` (although, maybe that needs to change). Specifically:

 * VMs are identified by UUID rather than name
 * All responses are nested in `miniccc_responses`.

Perhaps we could have:

```
miniccc/
	responses/
		<command id>/
			<name>/
	tails/
		(some structure)
```

**Comment by jcrussell** [comment]
`cc shadow` is growing on me.

**Comment by jcrussell** [comment]
@djfritz backtracked about a quarter mile:

https://blog.gopheracademy.com/advent-2014/fuse-zipfs/

We could have a FUSE layer over miniccc so that we can mount the VM's file system and then tail the files locally. This would make VMs on-par with containers which have a `fs` directory.

**Comment by djfritz** [comment]
This was @floren 's idea. I wouldn't dare suggest we add a fuse dependency...

**Comment by jcrussell** [comment]
`miniplumber` supersedes this, right?

**Comment by djfritz** [comment]
Yep
