### ISSUE TITLE
minimega: uptime per each VM

### ISSUE THREAD

**Issue by bjwrigh** [sandia-minimega/minimega#811]
Create a per-VM uptime record.  May exist but not shown on web.

**Comment by jasoncontrib** [comment]
Doesn't seem to exist for VMs, but we could add it by keeping track of how long a VM has been in the `RUNNING` state. This would not be the same as an `uptime` command from within the VM, of course.

@jcrussell @djfritz Thoughts?

**Comment by jcrussell** [comment]
What's the use case?

**Comment by djfritz** [comment]
I could see adding a launch time in the VM struct and simply indicating how
long the VM has been launched, but the tally of running time seems odd.

**Comment by jcrussell** [comment]
We have total CPU time in `vm top`. Is that sufficient?

**Comment by djfritz** [comment]
Should we add a wall clock time (time since launch) to top as well?

**Comment by jcrussell** [comment]
Add to `vm info`.
