### ISSUE TITLE
minimega: qemu kvm vga flag cirrus versus std

### ISSUE THREAD

**Issue by jasoncontrib** [sandia-minimega/minimega#825]
Is there a reason why minimega uses `-vga cirrus` instead of `-vga std`? QEMU's default video driver changed to `std` a couple of years ago, and `cirrus` is apparently quite outdated:

https://www.kraxel.org/blog/2014/10/qemu-using-cirrus-considered-harmful/

**Comment by djfritz** [comment]
Legacy flags from qemu 1.0 linger sometimes...

**Comment by jasoncontrib** [comment]
Any danger to switching it over to `std`? Worries about 20-year old guest OS's that'll stop booting?

**Comment by djfritz** [comment]
I'm fine with it. @floren should chime in though on possible issues he may
know of. We can always change it back or make people override it if it
creates a problem.

**Comment by floren** [comment]
Nope, I've used -std in the past via an override and it seems fine

**Comment by jcrussell** [comment]
Could add `vm config vga` and set the default to `std`.

**Comment by djfritz** [comment]
I don't see a need to add a new API around this. It's never come up before.
Let's just change the hardcoded value for now.

**Comment by floren** [comment]
Yeah, in the rare cases where the cirrus VGA didn't work, I just used a
qemu override to set std. In the extremely rare cases where std doesn't
work, users can do the same.

john

**Comment by nullibadge** [comment]
windows xp needs std

**Comment by mkunz7** [comment]
windows xp needs this
