### ISSUE TITLE
minimega: container tasks not populated

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#828]
Ran the following:

```
vm config filesystem $containerfs
vm launch container 4
vm start all
```

And

```
# cat /sys/fs/cgroup/freezer/minimega/3/tasks
```

is empty. As a result, the VM keeps running even when paused.

**Comment by jcrussell** [comment]
Happened again with 3/4 of the containers.

**Comment by djfritz** [comment]
There's a race to be found. In VMs that have this issue, the container immediately returns from the freezer sync point in the launch routine:

    2017/01/06 20:50:57 DEBUG containerShim: 2017/01/06 20:50:57 DEBUG container.go:527: sync for freezing
    2017/01/06 20:50:57 DEBUG server.go:150: ListenUnix: /tmp/minimega/4/fs/cc
    2017/01/06 20:50:57 DEBUG containerShim: 2017/01/06 20:50:57 DEBUG container.go:533: return from freezing
