### ISSUE TITLE
Feature Request: noVNC mobile

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#848]
The stock version of novnc has buttons for:
panning, mouse click, open keyboard, and paste txt

Is there a reason why we are not showing these? Novnc seems to work from mini on my iphone, but I need those buttons to actually be able to use it.

**Comment by mkunz7** [comment]
https://github.com/sandia-minimega/minimega/pull/859

**Comment by jcrussell** [comment]
We merged #924, closing this.
