### ISSUE TITLE
Question: can preinit be used to inject files from host into container filesystem?

### ISSUE THREAD

**Issue by activeshadow** [sandia-minimega/minimega#854]
Just curious if I can use the `vm config preinit` option to inject, as an example, static network config files into a container before it starts. If so, is there a predetermined path or env variable I can use in the preinit script to point to the location of the container's root filesystem?

If not, any chance we could get a `vm config volume` option for containers? I could take a stab at implementing it...

**Comment by jcrussell** [comment]
It would be pretty trivial to set an environment variable for the container's name and filesystem directory before running the preinit script.

What would `vm config volume` provide? Additional overlays?

**Comment by activeshadow** [comment]
Once fully implemented, it'd be cool to see `vm config volume` provide something akin to Docker volumes, wherein you can share directories from the host into a container, and if marked as read-write also write to said shared directories from a container. So yes, additional overlays.

But... having access to env variables that point to the container's root filesystem in the `preinit` script would be awesome to have in the short term.

**Comment by djfritz** [comment]
We could add a volumes api pretty easily. We already bind mount a bunch of other stuff into the container.

**Comment by activeshadow** [comment]
Yeah, an actual volumes API would be beneficial as it would allow us to connect processes in containers to unix sockets on the host via a volume mount.

As an example, this might allow SCEPTRE to move away from a management plane for RTUs exposed on the experiment plane if we can run a unix-socket-to-tcp-socket ZMQ proxy on hosts that can route ZMQ comms from within an RTU container to the Kronos provider running in the management plane.
