### ISSUE TITLE
minimega: reflection magic for vms

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#86]
Original [issue 86](https://code.google.com/p/minimega/issues/detail?id=86) created by djfritz on 2015-01-22T01:27:29.000Z:

The VM code has a lot of redundancies for updating various fields in vmInfo before launching a VM (see vmConfigFns). With a little reflection magic, we could greatly simplify the VM code (and elsewhere, probably). I put together a small example on the Go playground [0]. Basically, I want to annotate fields in vmInfo with &quot;mm&quot; tags and then use reflection to handle update/clear/print for all the simple fields.

Thoughts?

[0] http://play.golang.org/p/fQdBNPgPus

**Comment by jcrussell** [comment]
Started on branch ticket-86.

**Comment by djfritz** [comment]
duplicate of #179
