### ISSUE TITLE
appengine build is broken

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#867]
Compile failed:
    2017/02/13 15:18:16 go-app-builder: build timing: 6×compile (1.792s total), 0×link (0s total)
    2017/02/13 15:18:16 go-app-builder: failed running compile: exit status 1
    
    dir.go:48: undefined: f_root
    dir.go:112: undefined: f_root
    dir.go:126: undefined: f_root
    dir.go:154: undefined: f_root
    dir.go:213: undefined: f_root
    mega.go:31: undefined: f_exec
    mega.go:54: undefined: f_root
    minimega.go:23: undefined: f_minimega
    --- end server output ---
    03:18 PM Rolling back the update.
    Error 422: --- begin server output ---
    
    --- end server output ---

**Comment by jcrussell** [comment]
Fixed by #868.
