### ISSUE TITLE
miniweb: add namespace as optional path parameter

### ISSUE THREAD

**Issue by derhart** [sandia-minimega/minimega#870]
We have experiments that we deploy in separate namespaces that have the same virtual machine name. For instance, there is a server1 in namespace foo and a server1 in namespace bar. The VNC web path resolves to http://<ip>:9001/connect/server1 for both, and this is making it impossible to connect to one of the boxes. Can you update the path to be namespace aware?

**Comment by derhart** [comment]
This looks to be intermittent, so I'm wondering if there's a race condition coming into play. I haven't found a clear pattern to what causes it though.

**Comment by jcrussell** [comment]
This is one of the features we want in miniweb. The current web will connect to whatever VM is in the active namespace of the head node.

**Comment by jcrussell** [comment]
@djfritz -- should we merge #852 and set a timeline for adding this?

**Comment by djfritz** [comment]
We can. Perhaps we should change the behavior to use the current namespace if none is specified (current behavior), and allow for a larger URL for namespace specific conns:

    # connect to server1 in the current namespace
    http://.../connect/server1

    # connect to server1 in a specific namespace
    http://.../connect/foo/server1

Thoughts?

@jcrussell

**Comment by djfritz** [comment]
Later on we can enforce namespace-specific constraints in miniweb with a -namespace flag or something, and that could disable the above feature.

**Comment by jcrussell** [comment]
I think adding the namespace as a path parameter makes sense and it wouldn't be simple to add.
