### ISSUE TITLE
minicli: Tab completion

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#88]
Original [issue 88](https://code.google.com/p/minimega/issues/detail?id=88) created by djfritz on 2015-01-29T00:48:27.000Z:

Support tab completion in minicli.

**Comment by floren** [comment]
does apropos help eliminate this need?

**Comment by jcrussell** [comment]
It would still be nice to be able to do `vm config<TAB>` and see a list of all the patterns that match that prefix.
