### ISSUE TITLE
Feature Request: vm config serialcc false

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#896]
By default mini adds a serial interface for cc. I have a vm that I need a serial adapter on and crashes when presented two. 

As a workaround I've been usIng qemu-override but this isn't ideal since the serial port is created using the id # and afaik I can't regex string replace. So I have to know what the vm id # is gonna be before string replacing it, thankfully it just increments. 

A vm config kvmmod false to remove -enable-kvm would help too when I change the qemu binary to arm.

**Comment by jcrussell** [comment]
It should be pretty trivial to add `vm config cc <true,false>`.

Do we even need the `-enable-kvm` flag? We currently start VMs with `kvm` which adds `-machine accel=kvm` to the command string. Is `-machine accel=kvm` == `-enable-kvm`?
