### ISSUE TITLE
Minimega: generate a Debian package for minimega

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#90]
Original [issue 90](https://code.google.com/p/minimega/issues/detail?id=90) created by djfritz on 2015-01-29T22:03:57.000Z:

Do the necessary configuration so we can create a Debian .deb package at-will, for example by running a ./debian.bash script.

**Comment by djfritz** [comment]
Is this done? Can we get some language in the docs for building the deb and close this?

**Comment by floren** [comment]
finally found the laptop that had the work, gonna try to get this in today

**Comment by djfritz** [comment]
Done via https://github.com/sandia-minimega/minimega/pull/152
