### ISSUE TITLE
minimega/ron: cc is broken with namespaces

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#900]
`ron` assumes that UUIDs are unique and tracks clients based on them but with namespaces, they may not be unique anymore. This also affects the filesystem for `miniccc_responses`.

**Comment by djfritz** [comment]
Ughh....

**Comment by djfritz** [comment]
We need an 'ughh' label

**Comment by jcrussell** [comment]
This is definitely a 'ughhh'.

**Comment by jcrussell** [comment]
Fixed in #915.
