### ISSUE TITLE
Record comments in CLI history

### ISSUE THREAD

**Issue by djfritz** [sandia-minimega/minimega#91]
Original [issue 91](https://code.google.com/p/minimega/issues/detail?id=91) created by djfritz on 2015-02-02T19:31:39.000Z:

Comments are stripped from the input text so there's currently no way to record them in the history. Is there a simple way to change how history is recorded to accommodate recording comments in the history?

**Comment by djfritz** [comment]
Is this done?

**Comment by jcrussell** [comment]
Yup, done. Think it was closed around the time that we transitioned from Google Code.
