### ISSUE TITLE
Feature request: vm config machine

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#910]
similar to:
```
vm config cpu core2duo
```
Can we implement
```
vm config machine q35
```
Having to do this gets annoying
```
vm config qemu-override "-enable-kvm" "-machine q35 -enable-kvm"
```

**Comment by jcrussell** [comment]
You could use `vm config qemu-append -machine q35` instead of `qemu-override`.

This is easy enough to add, what do you think @djfritz?
