### ISSUE TITLE
vm config net <alias>,<driver>,<mac>

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#914]
```
vm config net A,i82559c,5c:02:6a:00:11:22
```
This creates a network adapter with a vlan alias of i82559c instead of A
```
vm config net A,5c:02:6a:00:11:22
```
works as expected
as a workaround I've been using qemu overrides 
```
vm config net A,5c:02:6a:00:11:22
vm config qemu-override "e1000" "i82559c"
```

**Comment by jcrussell** [comment]
The driver should be last:

```
vm config net A,5c:02:6a:00:11:22,i82559c
```

I should add another example or make it clear that the complete order is:

```
bridge,VLAN,MAC,driver
```
