### ISSUE TITLE
minirouter kvm

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#917]
I can't get the kvm build of minirouter to work. A few issues.

1. kvm build instructions neglect to include copying over miniccc as well as minirouter
2. After copying over the miniccc binary and rebuildilng. The generated kvm boots, but doesn't launch miniccc successfully only minirouter.
3. Manually launching miniccc -serial /dev/virtio-ports/cc will generate an error about minirouter not being in the path. Manually setting the path with export PATH=$PATH:/ fixes this error and miniccc runs as expected.
4. Until minirouter is issued a commit which kills miniccc throwing an error on line 205 in commands.go exit status 1

running latest mini from source

**Comment by djfritz** [comment]
Looking at this now

**Comment by jcrussell** [comment]
This is my build script:

```
mirror="http://mirrors.cat.pdx.edu/debian"

cp bin/miniccc misc/vmbetter_configs/miniccc_virtio_overlay/
cp bin/miniccc misc/vmbetter_configs/minirouter_overlay/
cp bin/minirouter misc/vmbetter_configs/minirouter_overlay/

bin/vmbetter -mirror=$mirror -level info misc/vmbetter_configs/miniccc_virtio.conf
bin/vmbetter -mirror=$mirror -level info misc/vmbetter_configs/minirouter.conf
```

You may need to build with `-branch stable`.

**Comment by mkunz7** [comment]
I used stable

**Comment by jcrussell** [comment]
What did you build `miniccc` and `minirouter` on? We've had some issues with shared library versions.

**Comment by mkunz7** [comment]
```
root@silver3:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```
built using
```
# apt-get install squashfs-tools syslinux debootstrap genisoimage extlinux
# cd /home/ubuntu/minimega
# cp bin/miniccc misc/vmbetter_configs/minirouter_overlay/
# cp bin/minirouter misc/vmbetter_configs/minirouter_overlay/
# ./bin/vmbetter -branch stable -qcow -level debug -mbr /usr/lib/syslinux/mbr/mbr.bin misc/vmbetter_configs/minirouter.conf
```

**Comment by jcrussell** [comment]
Ah, there's the problem -- you can't use `-qcow`.

Our `/init` doesn't run when you build a qcow. We usually build initrd/kernel.

**Comment by mkunz7** [comment]
http://minimega.org/articles/router.article

tells you to use it

How do you build the initrd/kernel?

**Comment by djfritz** [comment]
Just omit -qcow

**Comment by mkunz7** [comment]
didn't work

it succesfully generated a minirotuer.initrd and minirouter.kernel

but it boots to a kernel panic, no working init found

**Comment by mkunz7** [comment]
I changed the ram from 1024 to 2048 and it boots now.

Mini commands issue without miniccc crashing and ipv4 networking works woot!

The console compalined about ospf1 on ethX though...

![screen shot 2017-05-17 at 3 54 58 pm](https://cloud.githubusercontent.com/assets/5001991/26175788/73a72ec4-3b19-11e7-9f2e-73ec1ad9d94d.png)

**Comment by mkunz7** [comment]
```
router r0 interface 0 1.0.0.254/24
router r0 dhcp 1.0.0.254 range 1.0.0.1 1.0.0.250
router r0 interface 1 2.0.0.254/24
router r0 dhcp 2.0.0.254 range 2.0.0.1 2.0.0.250
router r0 route ospf 0 0
router r0 route ospf 0 1
router r0 commit
```
1.0.0.0/24 can't ping 2.0.0.0/24 which means ospf isn't working

^^ see screenshot above

**Comment by mkunz7** [comment]
It probably has something to do with the versioning of bird.

http://bird.network.cz/pipermail/bird-users/2014-June.txt

Can we just distribute a working initrd/kernel pairing on minimega.org and inject the latest miniccc/minirouter with a shell script?
```
mkdir -p test
cd test
zcat ../minirouter.initrd | cpio -idm
cp ../bin/miniccc test/
cp ../bin/minirouter test/
find . | cpio -o -c | gzip -9 > ../newinitrd
cd ..
rm -rf test/
```

**Comment by mkunz7** [comment]
while I'm on a comment spree, the link for the container image is dead

old link:
https://storage.googleapis.com/minimega-files/minimega-2.2-containerfs.tar.bz2

current link:
https://storage.googleapis.com/minimega-files/minimega-2.3-minirouter.tar.bz2

**Comment by mkunz7** [comment]
bird 1.4.5 (debian stable)
bird 1.5.0 (minirouter.tar.bz2)
bird 1.6.3 (debian unstable)

switching to unstable fixes things, but you need to manually enable ipv4 forwarding with 
```sysctl -w net.ipv4.ip_froward=1```

**Comment by djfritz** [comment]
We have the ip forwarding flag in a separate file:

https://github.com/sandia-minimega/minimega/blob/master/misc/minirouter/preinit

Because containers can't set this flag at runtime - it has to happen before root capabilities are trimmed. Maybe we should have it in both and just let it fail in /init when running in a container but not when running as a full fledged vm...

**Comment by mkunz7** [comment]
it needs to be set inside the vm manually not on the host
