### ISSUE TITLE
minirouter static routing interface

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#919]
I have this network:
```
router r0 interface 0 1.0.0.200/24
router r0 dhcp 1.0.0.200 range 1.0.0.2 1.0.0.99
router r0 interface 1 1.0.0.201/24
router r0 interface 2 1.0.0.202/24

router r0 route static 1.0.0.0/24 1.0.0.200
router r0 route static 2.0.0.0/24 1.0.0.201
router r0 route static 3.0.0.0/24 1.0.0.202
router r0 commit

router r1 interface 0 1.0.0.101/24
router r1 interface 1 2.0.0.254/24
router r1 dhcp 2.0.0.254 range 2.0.0.1 2.0.0.250
router r1 route static 1.0.0.0/24 1.0.0.101
router r1 commit

router r2 interface 0 1.0.0.102/24
router r2 interface 1 3.0.0.254/24
router r2 dhcp 3.0.0.254 range 3.0.0.1 3.0.0.250
router r2 route static 1.0.0.0/24 1.0.0.102
router r2 commit
```
The bird config sets the routing table to route 1.0.0.0/24 traffic to 2.0.0.0/24 out 1.0.0.201 as expected, but it implies 1.0.0.201 is on eth0 which is not always the case as in this example it is on eth2.

I think in the bird config you can just specify the interface instead of dorking with the gateway.
```route 3.0.0.0/24 via "eth2";```

We should handle this case.

![diagram](https://cloud.githubusercontent.com/assets/5001991/26437714/5ab0457e-40e4-11e7-9d11-915776a7859d.png)

**Comment by mkunz7** [comment]
Part of my issue is I'm using the wrong ip as the next-hop address.

-remove- router r0 route static 1.0.0.0/24 1.0.0.200
router r0 route static 2.0.0.0/24 1.0.0.**101**
router r0 route static 3.0.0.0/24 1.0.0.**102**
router r1 route static 1.0.0.0/24 1.0.0.**201**
router r2 route static 1.0.0.0/24 1.0.0.**202**

The issue with bird creating a routing table that forces the traffic out eth0 remains.

Moving r1 and r2's link to r1 off 1.0.0.0/24 fixes it. 
IE
```
router r0 interface 0 1.0.0.254/24
router r0 dhcp 1.0.0.254 range 1.0.0.2 1.0.0.253
router r0 interface 1 11.0.0.1/24
router r0 interface 2 12.0.0.1/24

router r0 route static 2.0.0.0/24 11.0.0.2
router r0 route static 3.0.0.0/24 12.0.0.2
router r0 commit

router r1 interface 0 11.0.0.2/24
router r1 interface 1 2.0.0.254/24
router r1 dhcp 2.0.0.254 range 2.0.0.1 2.0.0.253
router r1 route static 1.0.0.0/24 11.0.0.1
router r1 commit

router r2 interface 0 12.0.0.2/24
router r2 interface 1 3.0.0.254/24
router r2 dhcp 3.0.0.254 range 3.0.0.1 3.0.0.253
router r2 route static 1.0.0.0/24 12.0.0.1
router r2 commit
```

**Comment by jcrussell** [comment]
It sounds like this is resolved.

**Comment by mkunz7** [comment]
How did this get resolved afaik this is still an issue. Here's the full example.

```
vm config filesystem /home/ubuntu/minirouterfs/
vm config fifo 1
vm config init /init
vm config preinit /home/ubuntu/minirouterfs/preinit
vm config net A B C
vm launch container r0
vm config net B D
vm launch container r1
vm config net C E
vm launch container r2
vm start r0,r1,r2

vm config disk /home/ubuntu/tiny.qcow
vm config net A
vm launch kvm tinya
vm start tinya

vm config net D
vm launch kvm tinyd
vm start tinyd

vm config net E
vm launch kvm tinye
vm start tinye

router r0 interface 0 1.0.0.200/24
router r0 dhcp 1.0.0.200 range 1.0.0.2 1.0.0.99
router r0 interface 1 1.0.0.201/24
router r0 interface 2 1.0.0.202/24

router r0 route static 2.0.0.0/24 1.0.0.101
router r0 route static 3.0.0.0/24 1.0.0.102
router r0 commit

router r1 interface 0 1.0.0.101/24
router r1 interface 1 2.0.0.254/24
router r1 dhcp 2.0.0.254 range 2.0.0.1 2.0.0.250
router r1 route static 1.0.0.0/24 1.0.0.201
router r1 commit

router r2 interface 0 1.0.0.102/24
router r2 interface 1 3.0.0.254/24
router r2 dhcp 3.0.0.254 range 3.0.0.1 3.0.0.250
router r2 route static 1.0.0.0/24 1.0.0.202
router r2 commit
```

on r0 the routing table still thinks 2.0.0.0 and 3.0.0.0 are out veth0

```
/ # route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
1.0.0.0         *               255.255.255.0   U     0      0        0 veth0
1.0.0.0         *               255.255.255.0   U     0      0        0 veth1
1.0.0.0         *               255.255.255.0   U     0      0        0 veth2
2.0.0.0         1.0.0.101       255.255.255.0   UG    0      0        0 veth0
3.0.0.0         1.0.0.102       255.255.255.0   UG    0      0        0 veth0
```

**Comment by jcrussell** [comment]
Thought you meant the issue was resolved when you said:

```
Moving r1 and r2's link to r0 off 1.0.0.0/24 fixes it.
```

**Comment by mkunz7** [comment]
I was secretly hoping you had fixed it with https://github.com/jcrussell/minimega/commit/2654398e6838e6bb7ad7e39efda5dedaf8cf5be2

**Comment by djfritz** [comment]
So this is because you're specifying 100.0.0.0/24 as a /24, and there can only be one static route for a given subnet. Well, you can stack a hierarchy, but that doesn't apply in your use case.

If you insist on using IPs that close together, you'll need to subnet them accordingly, so say you use:

    100.0.0.245
    100.0.0.249
    100.0.0.253

It's perfectly ok to have those IPs as /24s (all on the same subnet) on one box, but you'll still only have a single route for that whole /24 in your routing table. If one interface dies, then it will fallback to the next available route, and so on. 

If you want these IPs, then you'd have to set them up (in this example) as /30s:

    100.0.0.245/30 # ips 245-246, network is 244, broadcast is 247
    100.0.0.249/30 # ips 249-250, network is 248, broadcast is 251
    100.0.0.253/30 # ips 253-254, network is 252, broadcast is 255

A /30 has 4 ips in it, one for the network, one for broadcast, and the remaining 2 for use by you and your peered router.
