### ISSUE TITLE
minirouter cli bare metal

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#925]
With minirouter running and miniccc phoning home over tcp to minimega on bare metal, how in minimega do I configure minirouter?

I can't just use
```
router <vm name> <commands> 
```
Because there is no vm.

I could use minirouter -u, but I don't have the generated configs unless I export them from a configured vm.

**Comment by jcrussell** [comment]
I think we should use `rond` for physical nodes -- `minimega` should only deal with VMs. We could create a similar `router` API in `rond` ... that's a little messy though.
