### ISSUE TITLE
miniplumber

### ISSUE THREAD

**Issue by mkunz7** [sandia-minimega/minimega#927]
It's been a while since I used miniplumber, but I don't think it's working right anymore...

On host:
```
tmux new -s miniplumber -d
tmux send-keys -t miniplumber "/miniccc -parent 10.0.0.1" C-m
/miniccc -pipe foo
```
From mini:
```
$ pipe foo hello
```

![error](https://user-images.githubusercontent.com/5001991/27099162-abb25c90-503f-11e7-8352-a2376624cced.PNG)
![error2](https://user-images.githubusercontent.com/5001991/27099413-782ee4f0-5040-11e7-952a-30839c39a3f4.PNG)

**Comment by djfritz** [comment]
Yep this is a regression from https://github.com/sandia-minimega/minimega/commit/d773e7504db3a5b96f370ade652e08623c378425

Fix should be easy - incoming.
