### ISSUE TITLE
Bridges and Taps are not Thoroughly Cleaned Up After Force Quit

### ISSUE THREAD

**Issue by xchenan** [sandia-minimega/minimega#943]
The following script is one of the many which force minimega to quit:
```
vm config kernel <kernel>
vm config initrd <initrd>
vm config serial-ports 1 (if necessary)
vm config net <name of network>
bridge trunk mega_bridge <name of physical interface>
vm launch kvm test
vm start all
clear all
```

With the script above, mega_bridge is created and some mega_tap is attached to it. A physical interface of local machine is attached to mega_bridge as well. Unless the mega_bridge is removed, the local machine will lose it's connection to network.

However, the last command line in the script, ```clear all```, leads to force quit of minimega. In this case, mega_brigde and mega_tap are not removed successfully.  

![image](https://user-images.githubusercontent.com/6829866/28433968-8c93b046-6d42-11e7-8abc-2603e07813e9.png)

Hence those have to be removed manually. One approach to do so is:
```
sudo ovs-vsctl del-port mega_bridge <name of physical interface>
sudo ovs-vsctl del-br mega_bridge
sudo ip link delete <any mega_tap that still exists>
```
Please note that ```ip addr``` may help you to beware of the taps that are still uncleaned.

I propose that functionalities may need to be added so that when force quit happens, bridges and taps are also guaranteed to be removed.

**Comment by jcrussell** [comment]
We typically use `nuke` to cleanup state after a crash rather than trying to cleanup while crashing. Does this work for you?

**Comment by djfritz** [comment]
There are reasons NOT to cleanup on a crash - the VM and network state can continue, allowing you to finish a test or at least get data out before cleaning up.
