### ISSUE TITLE
minimega: restructure `router` API

### ISSUE THREAD

**Issue by jcrussell** [sandia-minimega/minimega#949]
Proposal: change `router` API to be like `vm config` by removing `<vm>` from each of the commands. For example:
```
router <vm> <log,> <level,> <fatal,error,warn,info,debug>
router <vm> <interface,> <network> <IPv4/MASK or IPv6/MASK or dhcp>
router <vm> <dhcp,> <listen address> <range,> <low address> <high address>
```
becomes:
```
router <config,> <log,> <level,> <fatal,error,warn,info,debug>
router <config,> <interface,> <network> <IPv4/MASK or IPv6/MASK or dhcp>
router <config,> <dhcp,> <listen address> <range,> <low address> <high address>
```
You then apply the current config to a VM with:
```
router <commit,> <vm target>
```
This way, you can reuse some configs and you don't have to have the VM in order to use `router config`. For example:

```
vm config ...
vm config ...
router config ...
router config ...
vm launch routerA
router commit routerA
```

We can also add `router save`/`router restore`/`router clone` APIs.

Thoughts?

**Comment by nullibadge** [comment]
Can we commit to minirouter multiple times?

I.e. Boot a network, configure the routers, and then at a later time make a change like adding a dns entry. 

To me the syntax for Vm config has this feel that we are setting the config in stone and once we boot a vm we can't change it. I like this idea of merging the syntax, but am worried this mindset will follow router config.

**Comment by mkunz7** [comment]
Can we commit to minirouter multiple times?

I.e. Boot a network, configure the routers, and then at a later time make a change like adding a dns entry.

To me the syntax for Vm config has this feel that we are setting the config in stone and once we boot a vm we can't change it. I like this idea of merging the syntax, but am worried this mindset will follow router config.

**Comment by jcrussell** [comment]
I agree that we should continue to support updates. The new workflow would be:

```
router config clone <vm>
router config ... # as many changes as needed
router commit <vm>
```
